import { Blues } from "./Blues"


export enum Type {
  'Super' = 1,
  'Genre' = 2,
  'Sub' = 3,
  'Scene' = 4,
  'Fusion' = 5
}

const AfricanFolk = [
  {
    type: Type.Sub,
    parent: Type.Genre,
    label: 'African Folk Music',
    id: 'african-folk',
    desc: 'Indigenous music of Africa that is passed down orally from generation to generation, the authors of the songs are usually unknown.',
    hard: ['contemporary-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Ambasse bey',
    id: 'ambasse-bey',
    desc: 'Indigenous music of Africa that is passed down orally from generation to generation, the authors of the songs are usually unknown.',
    hard: ['african-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Apala',
    id: 'apala',
    desc: 'Yoruba Music developed by Muslims during the late 1930s and early 1940s in the Ijebu region of Yorubaland, the current Ogun state.',
    hard: ['african-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Batuque',
    id: 'batuque',
    desc: "Tradition from Cape Verde, unusual among the islands' music due to its lack of polyphonic singing and its usage of polyrhythms.",
    hard: ['african-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Dagomba Music',
    id: 'dagomba-music',
    desc: 'Music of the Dagomba people of northern Ghana.',
    hard: ['african-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Gnawa',
    id: 'gnawa',
    desc: 'Mixture of Sub-Saharan African, Arabic, and Amazigh Music, created by the Gnawa, an ethnic minority group in North Africa, mainly Morocco.',
    hard: ['african-folk'],
    soft: ['arabic-music', 'amazigh-music'],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Kabye Folk Music',
    id: 'kabye-folk-music',
    desc: 'Traditional Folk Music of the Kabye people of northern Togo, including some of the most singular styles that can be found in West Africa.',
    hard: ['african-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Kilapanga',
    id: 'kilapanga',
    desc: 'Tradition of the Bakongo people from Angola and Congo that has influenced contemporary styles such as Kuduro.',
    hard: ['african-folk'],
    soft: ['kuduro'],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Malagasy Folk Music',
    id: 'malagasy-folk-music',
    desc: 'Melodic, chordophone-dominated sound; based on the Austronesian Music of the first settlers that arrived on the island from Borneo.',
    hard: ['african-folk'],
    soft: ['austronesian-music'],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Mbenga-Mbuti Music',
    id: 'mbenga-mbuti-music',
    desc: 'Music of the Mbenga and Mbuti people, Pygmy ethnic groups in Central Africa.',
    hard: ['african-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Moutya',
    id: 'moutya',
    desc: 'Tradition that originated in Seychelles among Creole slaves, similar to Séga, although rawer and played only on large flat drums made from goatskin.',
    hard: ['african-folk'],
    soft: ['sega'],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Ngoma',
    id: 'ngoma',
    desc: 'Played in Swahili-speaking African countries; primarily focused on rhythm.',
    hard: ['african-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Unyago',
    id: 'unyago',
    desc: 'Traditional music from Zanzibar, traditionally played at womens initiation rituals and weddings.',
    hard: ['ngoma'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Southern African Folk',
    id: 'southern-african-folk',
    desc: 'Traditional Folk Music of southern Africa.',
    hard: ['african-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Afrikaner Folk',
    id: 'afrikaner-folk',
    desc: 'Musical traditions developed by the Afrikaner community in southern Africa.',
    hard: ['southern-african-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Khoisan Folk ',
    id: 'khoisan-folk',
    desc: 'Encompasses traditions of the Khoisan ethnic family groups.',
    hard: ['southern-african-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Nguni Folk',
    id: 'nguni-folk',
    desc: 'Traditions of the Nguni ethnic family groups, a southern Bantu ethnicity.',
    hard: ['southern-african-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Sotho-Tswana Folk',
    id: 'sotho-tswana-folk',
    desc: 'Traditional Folk Music of the Sotho-Tswana ethnic family groups from southern Africa.',
    hard: ['southern-african-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Tchinkoume',
    id: 'tchinkoume',
    desc: 'Tradition from the central region of Benin around Savalou, played with water percussion.',
    hard: ['african-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Traditional Maloya',
    id: 'traditional-maloya',
    desc: 'Derived from Traditional Séga, this is the original dance music of La Réunion.',
    hard: ['african-folk'],
    soft: ['traditional-sega'],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Traditional Séga',
    id: 'traditional-sega',
    desc: 'Séga dance music born in the 18th century, before its later adoption of Western pop elements.',
    hard: ['african-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Zinli',
    id: 'zinli',
    desc: 'Traditional rhythmic chanting and percussion adapted to multiple West African contexts in the 20th century.',
    hard: ['african-folk'],
    soft: [],
  },
]

const AmericanFolk = [
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'American Folk Music',
    id: 'american-folk',
    desc: 'Traces back through the history of European and West African settlement and migration to North America, including parts of northern Mexico and Canada in addition to the United States.',
    hard: ['traditional-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Appalachian Folk Music',
    id: 'appalachian-folk',
    desc: 'Folk of the Appalachian Mountains in the Eastern United States.',
    hard: ['american-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Old-Time',
    id: 'old-time',
    desc: 'Pre-Bluegrass North American string band styles, particularly those rooted in Appalachian Folk Music.',
    hard: ['appalachian-folk'],
    soft: [],
  },

  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Field Hollers',
    id: 'field-hollers',
    desc: 'Created by African-American slaves working on cotton plantations, featuring expressive vocals to no strict rhythm.',
    hard: ['american-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Fife and Drum Blues',
    id: 'fife-and-drum-blues',
    desc: 'Rooted in martial Fife and Drum Corps music, originated among Afro-American communities in Mississippi.',
    hard: ['american-folk'],
    soft: [],
  },

  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Ring Shout',
    id: 'ring-shout',
    desc: 'Ritual practiced by African-Americans in the US South, characterized by shouting, chanting and people dancing in a circle while praying and clapping.',
    hard: ['american-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Sacred Harp Singing',
    id: 'sacred-harp-singing',
    desc: 'Predominantly 19th-century English hymns with tunes derived from old folk melodies.',
    hard: ['american-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Spirituals',
    id: 'spirituals',
    desc: 'Predecessor to Gospel that began as unaccompanied singing by American slaves; shares some of the characteristics of Work Song.',
    hard: ['american-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Talking Blues',
    id: 'talking-blues',
    desc: 'American Folk Music with spoken or nearly spoken vocals; often features dry humor and social commentary.',
    hard: ['american-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Traditional Black Gospel',
    id: 'traditional-black-gospel',
    desc: 'Born out of Spirituals in the early 20th century with influence from Southern Gospel and Blues, often featuring passionate or energetic vocal performances, motifs of salvation, and testaments of hardship.',
    hard: ['american-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Traditional Cajun Music',
    id: 'traditional-cajun-music',
    desc: 'Earliest and most "pure" form of Cajun Music, employing basic rhythms and frequent fiddle double stops.',
    hard: ['american-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Traditional Country',
    id: 'traditional-country',
    desc: 'Closely aligned with American Folk Music and Blues roots, from country\'s inception in Appalachia and the American South until the popularity of Honky Tonk and Country Pop in the 1950s.',
    hard: ['american-folk', 'blues'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Close Harmony',
    id: 'close-harmony',
    desc: 'Traditional two-part harmony singing performed mostly by brothers.',
    hard: ['traditional-country'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Country Gospel',
    id: 'country-gospel',
    desc: 'Incorporates the harmonies and Christian themes of Gospel.',
    hard: ['traditional-country'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Bluegrass Gospel',
    id: 'bluegrass-gospel',
    desc: 'Incorporates the religious topics and harmony vocals found in Country Gospel.',
    hard: ['country-gospel', 'traditional-bluegrass'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Country Yodeling',
    id: 'country-yodeling',
    desc: 'Vocal technique of Yodeling, brought to the United States by German settlers, sung over the instrumentation of Traditional Country.',
    hard: ['traditional-country'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Traditional Bluegrass',
    id: 'traditional-bluegrass',
    desc: 'Driving tempos, acoustic stringed instrumentation, and high vocal harmonies, adhering to the stylistic roots of the Bluegrass genre.',
    hard: ['traditional-country'],
    soft: [],
  },
]


export const Folk = [{
  type: Type.Super,
  label: 'Folk',
  id: 'folk',
  desc: 'Roots music from world culture, encompasing international tranditional folk',
  hard: [],
  soft: []
},

{
  type: Type.Genre,
  parent: Type.Super,
  label: 'Folk Rock',
  id: 'folk-rock',
  desc: 'A fusion genre combining elements of folk music and rock music, typically featuring acoustic instruments and lyrical storytelling.',
  hard: ['folk', 'rock'],
  soft: []
},

{
  type: Type.Genre,

  parent: Type.Super,
  label: 'Contemporary Folk',
  id: 'contemporary-folk',
  desc: 'Generally acoustic and modernized traditional folk music',
  hard: ['folk'],
  soft: []
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'American Primitivism',
  id: 'american-primitivism',
  desc: 'Blends avant-garde and neo-classical compositions with traditional Country Blues fingerpicking techniques.',
  hard: ['contemporary-folk'],
  soft: ['avant-garde', 'neo-classical'],
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Anti-Folk',
  id: 'anti-folk',
  desc: 'Rawer approach to folk, with an often self-mocking and sarcastic tone.',
  hard: ['contemporary-folk'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Super,
  label: 'Avant-Folk',
  id: 'avant-folk',
  desc: 'Experimental-influenced and playing with instrumentation, rhythm, and other factors not commonly found in folk.',
  hard: ['folk', 'avant-garde'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Free Folk',
  id: 'free-folk',
  desc: 'Incorporates improvisation, repetition and extended song lengths.',
  hard: ['avant-folk'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Campus Folk',
  id: 'campus-folk',
  desc: 'Born in Taiwan in the mid-1970s, this movement originated with university students creating their own modern-style songs in the wake of international tensions like Taiwan’s isolation from the United Nations and the United States’ embrace of the PRC as a diplomatic partner.',
  hard: ['contemporary-folk'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Chamber Folk',
  id: 'chamber-folk',
  desc: 'Gentle fingerpicked acoustic guitar or harp-led music that commonly includes a backing ensemble of harpsichords, strings, horns, or other orchestral instruments.',
  hard: ['contemporary-folk', 'chamber-music'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Country Folk',
  id: 'country-folk',
  desc: 'Emphasises Traditional Country instrumentation as well as influences from contemporary Singer-Songwriter traditions, such as a gentler disposition and prominent lyrical storytelling focus.',
  hard: ['contemporary-folk', 'country'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Folk Baroque',
  id: 'folk-baroque',
  desc: 'Originated in England in the early 1960s, featuring a distinctive guitar fingerpicking style of the same name and the DADGAD guitar tuning.',
  hard: ['contemporary-folk'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Folk Pop',
  id: 'folk-pop',
  desc: 'Blends Contemporary Folk with a Pop sensibility, most popular in the late 1960s and early 1970s and featuring influence from the contemporary Folk Rock style.',
  hard: ['contemporary-folk', 'pop'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Stomp and Holler',
  id: 'stomp-and-holler',
  desc: 'Highlights driving "stomping" rhythms and shouted group vocal harmonies, often drawing influences from Pop Rock, Indie Folk, and other genres, while maintaining a characteristically mellow and commercial sound.',
  hard: ['folk-pop'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Indie Folk',
  id: 'indie-folk',
  desc: 'Combines the melodic sensibilities and production style of Indie Rock and Indie Pop with acoustic instrumentation and influences from Folk, Singer-Songwriter, and sometimes Country.',
  hard: ['contemporary-folk', 'indie-rock', 'indie-pop'],
  soft: ['country', 'singer-songwriter'],
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Neofolk',
  id: 'neofolk',
  desc: 'Emerged in the mid-1980s from the Post-Industrial scene, with a dark, often martial atmosphere.',
  hard: ['contemporary-folk', 'post-industrial'],
  soft: ['martial-industrial'],
  bands: 'swans, sol invictus'
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Dark Folk',
  id: 'dark-folk',
  desc: 'Minimalistic and melancholic sound with influence from Nordic Folk Music and even Ambient.',
  hard: ['neofolk', 'nordic-folk-music'],
  soft: ['ambient'],
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Neofolklore',
  id: 'neofolklore',
  desc: 'Short-lived movement that reincorporated traditional Chilean folklore into modern production and styling inspired by foreign musicians.',
  hard: ['contemporary-folk'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Progressive Folk',
  id: 'progressive-folk',
  desc: 'Draws from a variety of sources to subvert traditional acoustic song forms, with diversity ranging from Jazz to Medieval music to various Regional Music traditions.',
  hard: ['contemporary-folk'],
  soft: ['folk', 'medieval', 'regional-music'],
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Psychedelic Folk',
  id: 'psychedelic-folk',
  desc: 'Acoustic forms that capture an atmosphere that is at turns dream-like, "spaced-out", whimsical, haunting, mystical, and melancholic.',
  hard: ['contemporary-folk'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Freak Folk',
  id: 'freak-folk',
  desc: 'Offshoot of the New Weird America movement characterised by acoustic and eclectic instruments, peculiar vocal styles, romantic lyrics, and a childlike atmosphere.',
  hard: ['psychedelic-folk'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Udigrudi',
  id: 'udigrudi',
  desc: 'Movement that emerged in the Brazilian city of Recife during the 1970s that combines psychedelic elements with music of Northeastern Brazil.',
  hard: ['psychedelic-folk', 'brazilian-music'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Wyrd Folk',
  id: 'wyrd-folk',
  desc: 'Closely tied to mysticism, old folk beliefs, and Folk Horror; often described as "witchy" or "pagan."',
  hard: ['psychedelic-folk'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Skiffle',
  id: 'skiffle',
  desc: 'Grew out of British Dixieland trad jazz, drawing influence from 1920s Jug Bands and the strong rhythms of 1950s Honky Tonk and Rock & Roll.',
  hard: ['contemporary-folk', 'jug-band'],
  soft: ['folk'],
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Xinyao',
  id: 'xinyao',
  desc: 'Singaporean Mandarin-language style, generally featuring harmonised group vocals and backed mainly by acoustic guitar.',
  hard: ['contemporary-folk'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Traditional Folk Music',
  id: 'traditional-folk',
  desc: 'Singaporean Mandarin-language style, generally featuring harmonised group vocals and backed mainly by acoustic guitar.',
  hard: ['contemporary-folk'],
  soft: [],
},
...AfricanFolk,
...AmericanFolk,
...Blues,
{
  type: Type.Scene,
  parent: Type.Super,
  label: 'Protest Music',
  desc: 'Scene that recollects all music connected to protest about social issues and political topics.',
  id: 'Protest-music',
  hard: ['folk', 'roots-regae', 'conscious-hiphop', 'punk', 'work-music', 'crust-punk', 'anarcho-punk'],
  soft: []
},
]
