import { Blues } from "./Blues"


export enum Type {
  'Super' = 1,
  'Genre' = 2,
  'Sub' = 3,
  'Scene' = 4,
  'Fusion' = 5
}

const AfricanFolk = [
  {
    type: Type.Sub,
    parent: Type.Genre,
    label: 'African Folk Music',
    id: 'african-folk',
    desc: 'Indigenous music of Africa that is passed down orally from generation to generation, the authors of the songs are usually unknown.',
    hard: ['contemporary-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Ambasse bey',
    id: 'ambasse-bey',
    desc: 'Indigenous music of Africa that is passed down orally from generation to generation, the authors of the songs are usually unknown.',
    hard: ['african-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Apala',
    id: 'apala',
    desc: 'Yoruba Music developed by Muslims during the late 1930s and early 1940s in the Ijebu region of Yorubaland, the current Ogun state.',
    hard: ['african-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Batuque',
    id: 'batuque',
    desc: "Tradition from Cape Verde, unusual among the islands' music due to its lack of polyphonic singing and its usage of polyrhythms.",
    hard: ['african-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Dagomba Music',
    id: 'dagomba-music',
    desc: 'Music of the Dagomba people of northern Ghana.',
    hard: ['african-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Gnawa',
    id: 'gnawa',
    desc: 'Mixture of Sub-Saharan African, Arabic, and Amazigh Music, created by the Gnawa, an ethnic minority group in North Africa, mainly Morocco.',
    hard: ['african-folk'],
    soft: ['arabic-music', 'amazigh-music'],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Kabye Folk Music',
    id: 'kabye-folk-music',
    desc: 'Traditional Folk Music of the Kabye people of northern Togo, including some of the most singular styles that can be found in West Africa.',
    hard: ['african-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Kilapanga',
    id: 'kilapanga',
    desc: 'Tradition of the Bakongo people from Angola and Congo that has influenced contemporary styles such as Kuduro.',
    hard: ['african-folk'],
    soft: ['kuduro'],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Malagasy Folk Music',
    id: 'malagasy-folk-music',
    desc: 'Melodic, chordophone-dominated sound; based on the Austronesian Music of the first settlers that arrived on the island from Borneo.',
    hard: ['african-folk'],
    soft: ['austronesian-music'],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Mbenga-Mbuti Music',
    id: 'mbenga-mbuti-music',
    desc: 'Music of the Mbenga and Mbuti people, Pygmy ethnic groups in Central Africa.',
    hard: ['african-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Moutya',
    id: 'moutya',
    desc: 'Tradition that originated in Seychelles among Creole slaves, similar to Séga, although rawer and played only on large flat drums made from goatskin.',
    hard: ['african-folk'],
    soft: ['sega'],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Ngoma',
    id: 'ngoma',
    desc: 'Played in Swahili-speaking African countries; primarily focused on rhythm.',
    hard: ['african-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Unyago',
    id: 'unyago',
    desc: 'Traditional music from Zanzibar, traditionally played at womens initiation rituals and weddings.',
    hard: ['ngoma'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Southern African Folk',
    id: 'southern-african-folk',
    desc: 'Traditional Folk Music of southern Africa.',
    hard: ['african-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Afrikaner Folk',
    id: 'afrikaner-folk',
    desc: 'Musical traditions developed by the Afrikaner community in southern Africa.',
    hard: ['southern-african-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Khoisan Folk ',
    id: 'khoisan-folk',
    desc: 'Encompasses traditions of the Khoisan ethnic family groups.',
    hard: ['southern-african-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Nguni Folk',
    id: 'nguni-folk',
    desc: 'Traditions of the Nguni ethnic family groups, a southern Bantu ethnicity.',
    hard: ['southern-african-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Sotho-Tswana Folk',
    id: 'sotho-tswana-folk',
    desc: 'Traditional Folk Music of the Sotho-Tswana ethnic family groups from southern Africa.',
    hard: ['southern-african-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Tchinkoume',
    id: 'tchinkoume',
    desc: 'Tradition from the central region of Benin around Savalou, played with water percussion.',
    hard: ['african-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Traditional Maloya',
    id: 'traditional-maloya',
    desc: 'Derived from Traditional Séga, this is the original dance music of La Réunion.',
    hard: ['african-folk'],
    soft: ['traditional-sega'],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Traditional Séga',
    id: 'traditional-sega',
    desc: 'Séga dance music born in the 18th century, before its later adoption of Western pop elements.',
    hard: ['african-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Zinli',
    id: 'zinli',
    desc: 'Traditional rhythmic chanting and percussion adapted to multiple West African contexts in the 20th century.',
    hard: ['african-folk'],
    soft: [],
  },
]


const ArabicFolk = [
  {
    type: Type.Sub,
    parent: Type.Genre,
    label: 'Arabic Folk Music',
    id: 'arabic-folk',
    desc: 'Traditional Folk Music of the Arabic people.',
    hard: ['contemporary-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Aita',
    id: 'aita',
    desc: 'Arabic Folk Music from rural Morocco with piercing singing, scratchy viola, and rollicking hand drums.',
    hard: ['arabic-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Arabic Bellydance Music',
    id: 'arabic-bellydance',
    desc: 'Accompaniment to traditional belly dances.',
    hard: ['arabic-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Raqs baladi',
    id: 'raqs-baladi',
    desc: 'Egyptian folk dance and its associated musical accompaniment, appearing in the 20th century.',
    hard: ['arabic-bellydance'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Ayyalah',
    id: 'ayyalah',
    desc: 'Traditional Khaliji-Bedouin weapon performance, commonly found across the United Arab Emirates and Northwestern Oman.',
    hard: ['arabic-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Fijiri',
    id: 'fijiri',
    desc: 'Deeply rooted in the Persian Gulf pearl diving culture, and sung during weekly gatherings combining solo and choral sections with minimal percussion.',
    hard: ['arabic-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Liwa',
    id: 'liwa',
    desc: 'Traditional Khaliji performance with East African Music roots centered around the mizmar and traditional drums, typically sung in Khaliji Arabic and Swahili.',
    hard: ['arabic-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Nuban',
    id: 'nuban',
    desc: 'Traditional Afro-Emirati Folk performance of Nuban origin most commonly performed in the emirate of Dubai.',
    hard: ['arabic-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Sa\'idi',
    id: 'saidi',
    desc: 'Traditional folkloric performance and form of Arabic Folk Music originating from Upper Egypt.',
    hard: ['arabic-folk'],
    soft: [],
  }
]

const BrasilianFolk = [
  {
    type: Type.Sub,
    parent: Type.Genre,
    label: 'Brazilian Folk Music',
    id: 'brazilian-folk',
    desc: 'Comprises the various traditions of folk music found in Brazil, often resulting from the interplay of Indigenous, African and European music.',
    hard: ['contemporary-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Aboio',
    id: 'aboio',
    desc: 'Cattle-herding songs originating in rural Northeastern Brazil.',
    hard: ['brazilian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Aboio cantado',
    id: 'aboio-cantado',
    desc: 'Aboio that features rhyming verses.',
    hard: ['aboio'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Banda de pífano',
    id: 'banda-de-pifano',
    desc: 'Lively music played by bands consisting of two fifes and percussion.',
    hard: ['brazilian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Candomblé Music',
    id: 'candomble',
    desc: 'Music of the Afro-Brazilian Candomblé religion that influenced the secular Afoxé.',
    hard: ['brazilian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Cantoria',
    id: 'cantoria',
    desc: 'Sung poetry of itinerant cantadores from Northeastern Brazil.',
    hard: ['brazilian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Repente',
    id: 'repente',
    desc: 'Contest of fully improvised poetry sung in different stanza formats.',
    hard: ['cantoria'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Capoeira Music',
    id: 'capoeira',
    desc: 'Afro-Brazilian style that accompanies and sets the rhythm and energy of the capoeira martial art, originating in the 19th century with the relocation of African slaves to the states of Bahia and Rio de Janeiro.',
    hard: ['brazilian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Fandango caiçara',
    id: 'fandango-caicara',
    desc: 'Style of fandango born in coastal Southern Brazil amidst the Caiçara people.',
    hard: ['brazilian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Jongo',
    id: 'jongo',
    desc: 'Afro-Brazilian cultural manifestation involving music and dance; composed of percussion instruments and chants.',
    hard: ['brazilian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Ponto de umbanda',
    id: 'ponto-de-umbanda',
    desc: 'Afro-Brazilian religious ritualistic praise sung by priests to evoke entities; typically accompanied by claps and traditional drums known as atabaque.',
    hard: ['jongo'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Lundu',
    id: 'lundu',
    desc: 'Afro-Brazilian music and dance that emerged in the 18th century with influences from African drumming with European fandango.',
    hard: ['brazilian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Maracatu',
    id: 'maracatu',
    desc: 'Afro-Brazilian genre which accompanies the cultural manifestation of the same name, hailing from the northeastern state of Pernambuco.',
    hard: ['brazilian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Modinha',
    id: 'modinha',
    desc: 'Popular during the 18th and 19th centuries in Brazil; characterized by sentimental works with amorous themes, poetic lyrics, acoustic instrumentation and operatic vocals.',
    hard: ['brazilian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Rasqueado',
    id: 'rasqueado',
    desc: 'Regional dance and its accompanying music from the Brazilian midwest, predominantly the state of Mato Grosso.',
    hard: ['brazilian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Samba de roda',
    id: 'samba-de-roda',
    desc: 'Mixed Portuguese culture with African slave traditions, as well as sharing roots and similarities with Batuque and Jongo.',
    hard: ['brazilian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Sertanejo de raiz',
    id: 'sertanejo-de-raiz',
    desc: 'Earliest form of Sertanejo, emerging in pre-World War II rural Brazil during the late 1920s; quickly strummed acoustic guitars, most commonly the 10-string viola caipira and classical guitar, and a highly emotive vocal style.',
    hard: ['brazilian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Moda de viola',
    id: 'moda-de-viola',
    desc: 'Style of Sertanejo de raiz predominant in southeast, south, and west-central Brazil.',
    hard: ['sertanejo-de-raiz'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Toada de Boi',
    id: 'toada-de-boi',
    desc: 'Slow, heavy-percussed tunes celebrating the folkloric Ox, originally from Bumba-meu-boi June parties in Northeastern Brazil.',
    hard: ['brazilian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Xaxado',
    id: 'xaxado',
    desc: 'Features a strong rhythmic beat, sliding tap dances, and stories of backland bandits.',
    hard: ['brazilian-folk'],
    soft: [],
  },
]
const CanadianFolk = [
  {
    type: Type.Sub,
    parent: Type.Genre,
    label: 'Canadian Folk Music',
    id: 'canadian-folk',
    desc: 'Traditional folk of the European settlers who arrived in Canada.',
    hard: ['contemporary-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Canadian Maritime Folk',
    id: 'canadian-maritime-folk',
    desc: 'Traditional folk of Canada\'s Maritimes (Nova Scotia, Prince Edward Island, and New Brunswick).',
    hard: ['canadian-folk'],
    soft: [],
  },

  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'French-Canadian Folk Music',
    id: 'french-canadian-folk',
    desc: 'Brought by French colonists to their Nouvelle-France settlements, primarily based around French Folk Music with influences from English Folk Music and Celtic Folk Music, typically played during gatherings and holidays.',
    hard: ['canadian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Métis Fiddling',
    id: 'metis-fiddling',
    desc: 'Canadian style blending First Nations and European musical influences into an up-tempo style of fiddling characterized by the use of syncopation and indigenous rhythms.',
    hard: ['canadian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Newfoundland Folk Music',
    id: 'newfoundland-folk',
    desc: 'Traditional Folk Music of Newfoundland and Labrador, Canada\'s easternmost province.',
    hard: ['canadian-folk'],
    soft: [],
  },
]

const CaucasianFolk = [
  {
    type: Type.Sub,
    parent: Type.Genre,
    label: 'Caucasian Folk Music',
    id: 'caucasian-folk',
    desc: 'Folk of the Caucasus region, a mountainous area that connects Eastern Europe to Asia.',
    hard: ['contemporary-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Abkhazian Folk Music',
    id: 'abkhazian-folk',
    desc: 'Traditions of the Republic of Abkhazia, a disputed territory on the Black Sea in northwestern Georgia.',
    hard: ['caucasian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Chechen Folk Music',
    id: 'chechen-folk',
    desc: 'Folk of the Chechens, a Northeast Caucasian ethnic group predominantly living in the Republic of Chechnya, a federal subject of Russia.',
    hard: ['caucasian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Circassian Folk Music',
    id: 'circassian-folk',
    desc: 'Folk of the native Circassian peoples of Northern Caucasus, residing in the Republics of Adygea, Karachay-Cherkessia, and Kabardino-Balkaria respectively, which are federal subjects of the Russian Federation, as well as the territories of the former Ottoman Empire, with a significant diaspora population in modern Turkey.',
    hard: ['caucasian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Dagestani Folk Music',
    id: 'dagestani-folk',
    desc: 'Traditional Folk Music of the Dagestani people.',
    hard: ['caucasian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Avar Folk Music',
    id: 'avar-folk',
    desc: 'Traditional Folk Music of the Avar people.',
    hard: ['dagestani-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Georgian Folk Music',
    id: 'georgian-folk',
    desc: 'Traditions of the Georgian people, who mostly live in Georgia.',
    hard: ['caucasian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Batonebi Songs',
    id: 'batonebi-songs',
    desc: 'Traditional Georgian Lullabies often meant to soothe sick children.',
    hard: ['georgian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Ossetian Folk Music',
    id: 'ossetian-folk',
    desc: 'Folk music of Ossetians, an ethnic group that mainly inhabits a region located on both sides of the Greater Caucasus Mountains.',
    hard: ['caucasian-folk'],
    soft: [],
  },
]

const EastAsianFolk = [
  {
    type: Type.Sub,
    parent: Type.Genre,
    label: 'East Asian Folk Music',
    id: 'east-asian-folk',
    desc: 'All the forms of Traditional Folk Music from East Asia, including Japanese Folk Music, Chinese Folk Music, and Korean Folk Music.',
    hard: ['contemporary-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Amami shimauta',
    id: 'amami-shimauta',
    desc: 'Tradition from the Amami Islands, located in southern Japan.',
    hard: ['east-asian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Chinese Folk Music',
    id: 'chinese-folk',
    desc: 'Traditional folk of the Chinese people.',
    hard: ['east-asian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Chaozhou xianshi',
    id: 'chaozhou-xianshi',
    desc: 'Traditional and instrumental ensemble music originating from Chaozhou; played mainly on stringed instruments.',
    hard: ['chinese-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Han Folk Music',
    id: 'han-folk',
    desc: 'Chinese folk form often played at weddings and funerals, using the Suona (a form of oboe) and Chuigushou (a specific type of percussive ensemble), together with heterophony.',
    hard: ['chinese-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Haozi',
    id: 'haozi',
    desc: 'Chinese Work Song that originated from collective manual labor and usually follows a call-and-response structure, aiming to coordinate work.',
    hard: ['chinese-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Jiangnan sizhu',
    id: 'jiangnan-sizhu',
    desc: 'Originating from Jiangnan region and played by a varying ensemble of stringed instruments, flutes, mouth organs and small percussions.',
    hard: ['chinese-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Shan\'ge',
    id: 'shange',
    desc: 'Folk songs found in upland regions of China, typically sung while working.',
    hard: ['chinese-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Indigenous Taiwanese Music',
    id: 'indigenous-taiwanese',
    desc: 'Traditional Folk Music of the various Austronesian people groups that make up the indigenous population of the island of Taiwan.',
    hard: ['east-asian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Japanese Folk Music',
    id: 'japanese-folk',
    desc: 'Folk traditions of Japan.',
    hard: ['east-asian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Heikyoku',
    id: 'heikyoku',
    desc: 'Semi-classical bardic tradition in Japan analogous to the troubadour music of medieval Europe.',
    hard: ['japanese-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Kagura',
    id: 'kagura',
    desc: 'Performed at Shinto shrines for ceremonies and rituals.',
    hard: ['japanese-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Kouta',
    id: 'kouta',
    desc: 'Kouta, which literally means "little" or "short" song, is one type of the many varieties of Japanese folk songs that is distinguished by its briefness and wittiness.',
    hard: ['japanese-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Min\'yō',
    id: 'minyo',
    desc: 'Form of Japanese Folk Music which literally translates to "folk song".',
    hard: ['japanese-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Ondō',
    id: 'ondo',
    desc: 'Originally referred to the type of call-and-response form of Gagaku, but later became to be known for and distinguished by a swung 2/2 rhythm and storytelling.',
    hard: ['japanese-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Rōkyoku',
    id: 'rokyoku',
    desc: 'Storytelling usually accompanied by a shamisen.',
    hard: ['japanese-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Taiko',
    id: 'taiko',
    desc: 'Modern style of ensemble drumming, sometimes called kumi-daiko.',
    hard: ['japanese-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Tsugaru shamisen',
    id: 'tsugaru-shamisen',
    desc: 'Shamisen playing originating in the Tsugaru Peninsula of Aomori prefecture, recognizable in its percussive quality and special, slightly larger instrument.',
    hard: ['japanese-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Korean Folk Music',
    id: 'korean-folk',
    desc: 'Traditional Folk Music of the Korean people.',
    hard: ['east-asian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Muak',
    id: 'muak',
    desc: 'Korean shamanistic music that accompanies the ritual of gut as performed in all regions of Korea.',
    hard: ['korean-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Pansori',
    id: 'pansori',
    desc: 'Korean style of storytelling characterized by over-the-top, passionate singing from a solo vocalist accompanied by minimal drumming.',
    hard: ['korean-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Pungmul',
    id: 'pungmul',
    desc: 'Consists of drumming, dancing, and singing, and is a tradition deeply ingrained in South Korean culture.',
    hard: ['korean-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Sanjo',
    id: 'sanjo',
    desc: 'Traditional instrumental Korean Folk Music that focuses on a wide variety of rhythmic changes with many different classical Korean instruments.',
    hard: ['korean-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Sinawi',
    id: 'sinawi',
    desc: 'Improvisational genre traditionally serving as an accompaniment to Korean shamanic rituals.',
    hard: ['korean-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Vietnamese Folk Music',
    id: 'vietnamese-folk',
    desc: 'Traditional Folk Music of the Vietnamese people, with traditions influenced by both Chinese Music and Austronesian culture through the Cham people.',
    hard: ['east-asian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Chèo',
    id: 'cheo',
    desc: 'Northern Vietnamese folk musical theatre, characterized by minimal set design and satirical content.',
    hard: ['vietnamese-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Quan họ',
    id: 'quan-ho',
    desc: 'Tradition of the Northern Vietnamese provinces of Bắc Ninh and Bắc Giang, originally consisting of harmonic, a cappella singing from two competing duos.',
    hard: ['vietnamese-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Xẩm',
    id: 'xam',
    desc: 'Developed in Northern Vietnam, traditionally sung by blind bards accompanied by a đàn bầu or đàn nhị.',
    hard: ['vietnamese-folk'],
    soft: [],
  },
]

const EuropeanFolk = [
  {
    type: Type.Sub,
    parent: Type.Genre,
    label: 'European Folk Music',
    id: 'european-folk',
    desc: 'Encompasses numerous folk traditions found in Europe.',
    hard: ['contemporary-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Alpine Folk Music',
    id: 'alpine-folk',
    desc: 'Traditional Folk Music of the Alps, including parts of Germany, Austria, Slovenia, Switzerland, and Italy.',
    hard: ['european-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Canto degli Alpini',
    id: 'canto-degli-alpini',
    desc: 'Created and traditionally sung by choirs formed from the Italian army\'s Alpine mountain infantry corps, mainly dating back to WWI.',
    hard: ['alpine-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Ländler',
    id: 'lander',
    desc: 'Swiss-German dance band music based on the accordion, combining traditional Alpine Folk Music with elements from Schlager and Jazz.',
    hard: ['alpine-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Narodno zabavna glasba',
    id: 'narodno-zabavna-glasba',
    desc: 'Modernised form of Slovenian Folk Music from the Alpine region of Upper Carniola (Oberkrain).',
    hard: ['alpine-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Naturjodel',
    id: 'naturjodel',
    desc: 'Originated in Toggenburg and Appenzell in Switzerland; deep vocal range, relaxed voice, free tempo, polyphony, elongated notes, improvisation, glissando, and use of syllabic sounds.',
    hard: ['alpine-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Balkan Folk Music',
    id: 'balkan-folk',
    desc: 'Traditional Folk Music of the Balkan region of Southeastern Europe.',
    hard: ['european-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Albanian Folk Music',
    id: 'albanian-folk',
    desc: 'Traditional Folk Music of Albania, including the area\'s traditions as well as influence from Turkish Music.',
    hard: ['balkan-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Lab Polyphony',
    id: 'lab-polyphony',
    desc: 'One of several genres of iso-polyphonic music performed in southern Albania, with "iso" referring to the distinctive drone voice used.',
    hard: ['albanian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Musika popullore',
    id: 'musika-popullore',
    desc: 'Tradition in Albania consisting of light, commercial, amplified Albanian Folk Music usually professionally arranged and manufactured in recording studios alongside video clips.',
    hard: ['albanian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Tosk Polyphony',
    id: 'tosk-polyphony',
    desc: 'Polyphonic singing in the Toskëri region of southern Albania.',
    hard: ['albanian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Aromanian Folk Music',
    id: 'aromanian-folk',
    desc: 'Traditional Folk Music of the Aromanians.',
    hard: ['balkan-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Balkan Brass Band',
    id: 'balkan-brass-band',
    desc: 'Balkan Folk Music played by brass bands.',
    hard: ['balkan-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Bosnian Folk Music',
    id: 'bosnian-folk',
    desc: 'Traditional Folk Music of the Bosnians.',
    hard: ['balkan-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Izvorna bosanska muzika',
    id: 'izvorna-bosanska-muzika',
    desc: 'Polyphonic vocal music that developed in Bosnia in the 20th century, bearing connections to traditional Bosnian genres.',
    hard: ['bosnian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Sevdalinka',
    id: 'sevdalinka',
    desc: 'Melancholic folk song, originating from Bosnia and Herzegovina, typically love-themed and accompanied by instruments like guitar and accordion.',
    hard: ['bosnian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Bulgarian Folk Music',
    id: 'bulgarian-folk',
    desc: 'Consists of a variety of traditions and styles, with distinct sounds originating from current and historical regions such as Sofia, Dobrudzha, Macedonia and Thrace.',
    hard: ['balkan-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Croatian Folk Music',
    id: 'croatian-folk',
    desc: 'Traditional Folk Music of the Croats.',
    hard: ['balkan-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Klapa',
    id: 'klapa',
    desc: 'Traditional form characteristic of the Dalmatia region of Croatia rooted in littoral church singing.',
    hard: ['croatian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Csango Folk Music',
    id: 'csango-folk',
    desc: 'Folk of the Csango, an ethnic minority group with Hungarian origins living primarily in the Romanian Moldavia region, but who are also found in the Transylvania, Dobruja, Moldova, the Ukrainian Chernivtsi region, and the Tolna region of Hungary.',
    hard: ['balkan-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Gagauz Folk Music',
    id: 'gagauz-folk',
    desc: 'Gagauz people are a Turkic group living mostly in the southern Gagauzia region of Moldova, but also nearby areas like southwestern Ukraine and southeastern Romania.',
    hard: ['balkan-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Ganga',
    id: 'ganga',
    desc: 'Dissonant form of polyphonic singing from the regions of Herzegovina and Dalmatia.',
    hard: ['balkan-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Greek Folk Music',
    id: 'greek-folk',
    desc: 'Greek folk traditions.',
    hard: ['balkan-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Aegean Islands Folk Music',
    id: 'aegean-islands-folk',
    desc: 'Music of the Greek Aegean Islands.',
    hard: ['greek-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Cretan Folk Music',
    id: 'cretan-folk',
    desc: 'Folk of the Greek island Crete.',
    hard: ['greek-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Rizitika',
    id: 'rizitika',
    desc: 'Some of the oldest and most important types of vocal music on the Cretan island, characterized by its dramatic style of singing.',
    hard: ['cretan-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Dimotika',
    id: 'dimotika',
    desc: 'Traditional Folk Music of the Greek mainland, often using clarinet, guitar, tambourine, and violin as accompaniment, while also incorporating various forms of Greek dance and vocal music.',
    hard: ['greek-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Ionian Islands Folk Music',
    id: 'ionian-islands-folk',
    desc: 'Traditional Folk Music from the Ionian Islands in Greece.',
    hard: ['greek-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Rembetika',
    id: 'rembetika',
    desc: 'Greek tradition originating in traditional Mikrasiatiki and Smyrnaiki music with elements of other local traditional Greek genres.',
    hard: ['greek-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Macedonian Folk Music',
    id: 'macedonian-folk',
    desc: 'Folk music of Macedonians, a South Slavic ethnic group who are primarily associated with the Republic of Macedonia.',
    hard: ['balkan-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Čalgija',
    id: 'calgija',
    desc: 'Urban folk from Macedonia very popular in the 19th and 20th centuries performed by ensembles called Čalgii.',
    hard: ['macedonian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Montenegrin Folk Music',
    id: 'montenegrin-folk',
    desc: 'Traditional folk music of Montenegro.',
    hard: ['balkan-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Muzică lăutărească',
    id: 'muzica-lautareasca',
    desc: 'Strongly influenced by folk from Turkey, Russia, and Western Europe, and even by Byzantine Church music.',
    hard: ['balkan-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Serbian Folk Music',
    id: 'serbian-folk',
    desc: 'Traditional Folk Music of the Serbian people.',
    hard: ['balkan-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Starogradska muzika',
    id: 'starogradska-muzika',
    desc: 'Translated as "old city music", this is the urban traditional music of Macedonia and Serbia.',
    hard: ['balkan-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Baltic Folk Music',
    id: 'baltic-folk',
    desc: 'Traditional Folk Music of the Balts.',
    hard: ['european-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Latvian Folk Music',
    id: 'latvian-folk',
    desc: 'Traditional Folk Music of the Latvians.',
    hard: ['baltic-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Lithuanian Folk Music',
    id: 'lithuanian-folk',
    desc: 'The Traditional Folk Music of the Lithuanian people.',
    hard: ['baltic-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Sutartinės',
    id: 'sutartines',
    desc: 'Unique form of polyphonic vocal music originating from a small area of Northeastern Lithuania.',
    hard: ['lithuanian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Balto-Finnic Folk Music',
    id: 'balto-finnic-folk',
    desc: 'Traditional Folk Music of Balto-Finnic peoples.',
    hard: ['european-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Estonian Folk Music',
    id: 'estonian-folk',
    desc: 'Traditional Folk Music of the Estonian people.',
    hard: ['balto-finnic-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Seto leelo',
    id: 'seto-leelo',
    desc: 'Style of polyphonic singing of the Seto people.',
    hard: ['estonian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Finnish Folk Music',
    id: 'finnish-folk',
    desc: 'Traditional Folk Music of the Finnish people.',
    hard: ['balto-finnic-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Karelian Folk Music',
    id: 'karelian-folk',
    desc: 'Traditional Folk Music of the Karelian people.',
    hard: ['balto-finnic-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Livonian Folk Music',
    id: 'livonian-folk',
    desc: 'Traditional Folk Music of the Livonian people.',
    hard: ['balto-finnic-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Rune Singing',
    id: 'rune-singing',
    desc: 'Traditional vocal music of Baltic-Finnic peoples characterized by singing poems, performed solo or in groups.',
    hard: ['balto-finnic-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Basque Folk Music',
    id: 'basque-folk',
    desc: 'Traditional Folk Music of the Basque people.',
    hard: ['european-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Trikitixa',
    id: 'trikitixa',
    desc: 'Form of Basque folk music characterized by the use of accordion and tambourine.',
    hard: ['basque-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Catalan Folk Music',
    id: 'catalan-folk',
    desc: 'Blend of local styles and influences from the Iberian Peninsula region and the Catalonian area of Southern France.',
    hard: ['european-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Sardana',
    id: 'sardana',
    desc: 'Traditional dance dating from the 16th century performed by large ensembles called \'Cobla\' and danced by people holding hands in a circle.',
    hard: ['catalan-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Celtic Folk Music',
    id: 'celtic-folk',
    desc: 'Derived from Celtic traditions of Ireland, Scotland, Wales, Cornwall, the Isle of Man, Brittany, Galicia, Cantabria, Asturias, and Trás-os-Montes (Portugal).',
    hard: ['european-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Breton Celtic Folk Music',
    id: 'breton-celtic-folk',
    desc: 'Movement in the Brittany region of France which translated Celtic Folk Music from Ireland and Scotland into the Celtic Breton language.',
    hard: ['celtic-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Bagad',
    id: 'bagad',
    desc: 'Breton style performed by bands featuring bagpipes, bombardes, and percussion.',
    hard: ['breton-celtic-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Cape Breton Folk Music',
    id: 'cape-breton-folk',
    desc: 'Celtic Folk Music that emerged in Cape Breton, an island at the eastern shore of Nova Scotia, through immigrants from Scotland and Ireland.',
    hard: ['celtic-folk', 'canadian-maritime-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Cape Breton Fiddling',
    id: 'cape-breton-fiddling',
    desc: 'Distinctive Celtic fiddling originating from the Scottish immigrants who settled in Canada on Cape Breton Island.',
    hard: ['cape-breton-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Cornish Folk Music',
    id: 'cornish-folk',
    desc: 'Musical traditions developed by the Cornish people, mainly found in the county of Cornwall in South West England.',
    hard: ['celtic-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Irish Folk Music',
    id: 'irish-folk',
    desc: 'Traditional Folk Music of Ireland.',
    hard: ['celtic-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Sean-nós',
    id: 'sean-nos',
    desc: 'Highly ornamented, unaccompanied singing in the Irish language.',
    hard: ['irish-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Manx Folk Music',
    id: 'manx-folk',
    desc: 'Folk of the Isle of Man.',
    hard: ['celtic-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Scottish Folk Music',
    id: 'scottish-folk',
    desc: 'Traditional Folk Music of the Scottish people.',
    hard: ['celtic-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Òrain Ghàidhlig',
    id: 'orain-ghaidhlig',
    desc: 'Songs sung in Scottish Gaelic, often but not always unaccompanied.',
    hard: ['scottish-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Òrain luaidh',
    id: 'orain-luaidh',
    desc: 'Rhythmic call-and-response style song form that traditionally accompanied the production of tweed cloth through beating the material by hand to soften it after it came off the loom.',
    hard: ['orain-ghaidhlig'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Seinn nan salm',
    id: 'seinn-nan-salm',
    desc: 'Unaccompanied, rhythmically free-flowing psalm singing in Gaelic practiced by Presbyterian churches, which involves a call-and-response between the precentor and the congregation.',
    hard: ['orain-ghaidhlig'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Pìobaireachd',
    id: 'piobaireachd',
    desc: 'Art tradition which originated in the Scottish Highlands, usually associated with the Great Highland bagpipes.',
    hard: ['scottish-folk', 'classical'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Pipe Band',
    id: 'pipe-band',
    desc: 'Tradition originating in the Scottish military; standard instruments consist of 6-25 sets of Great Highland bagpipes, 3-10 military snare drums, 1-6 Scottish tenor drums, and one bass drum.',
    hard: ['scottish-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Scots Song',
    id: 'scots-song',
    desc: 'Traditional folk songs usually sung in Lowland Scots, often but not always unaccompanied.',
    hard: ['scottish-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Scottish Country Dance Music',
    id: 'scottish-country-dance',
    desc: 'Strict-tempo style played by Scottish country dance bands, led by an accordion or a fiddle and featuring piano, drums and sometimes double bass.',
    hard: ['scottish-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Shetland & Orkney Folk Music',
    id: 'shetland-and-orkney-folk',
    desc: 'Folk of the Shetland and Orkney Islands.',
    hard: ['scottish-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Welsh Folk Music',
    id: 'welsh-folk',
    desc: 'Traditions of the Welsh people.',
    hard: ['celtic-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Dutch Folk Music',
    id: 'dutch-folk',
    desc: 'Traditional Folk Music from the Netherlands.',
    hard: ['european-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'English Folk Music',
    id: 'english-folk',
    desc: 'Musical traditions of the English people, primarily divided into dance music and folksongs.',
    hard: ['european-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Northumbrian Folk Music',
    id: 'northumbrian-folk',
    desc: 'Traditional folk of Northumbria, a region of Northern England consisting of Northumberland and County Durham.',
    hard: ['english-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Scrumpy and Western',
    id: 'scrumpy-and-western',
    desc: 'Usually humorous music originating from England\'s West Country, heavily featuring traditional English folk instruments and often sung in the West Country accent.',
    hard: ['english-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Flemish Folk Music',
    id: 'flemish-folk',
    desc: 'Traditional Folk Music of the Flanders region in northern Belgium, typically sung in the local Flemish dialect.',
    hard: ['european-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'French Folk Music',
    id: 'french-folk',
    desc: 'Traditional Folk Music of metropolitan France, including that of its regional cultures.',
    hard: ['european-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Alsatian Folk Music',
    id: 'alsatian-folk',
    desc: 'Traditional music of the Alsatians.',
    hard: ['french-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Breton Folk Music',
    id: 'breton-folk',
    desc: 'Folk of the Brittany region in France, including Breton Celtic Folk Music and music in the regional Romance language, Gallo.',
    hard: ['french-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Kan ha diskan',
    id: 'kan-ha-diskan',
    desc: 'Call and response type of folk singing from Brittany.',
    hard: ['breton-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Corsican Folk Music',
    id: 'corsican-folk',
    desc: 'French folk from Corsica, sung mainly in Corsican and sometimes in French.',
    hard: ['french-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Paghjella',
    id: 'paghjella',
    desc: 'Traditional Polyphonic Chant from Corsica consisting of three registers of vocalists singing in a semicircle.',
    hard: ['corsican-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Musette',
    id: 'musette',
    desc: 'French popular music which arose in 1880s Paris, performed with the traditional instruments musette, grelottière, and accordion.',
    hard: ['french-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Swing musette',
    id: 'swing-musette',
    desc: 'Appeared in the 1930s in France, combination of Musette with Swing, mainly focusing on accordion playing.',
    hard: ['musette'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Occitan Folk Music',
    id: 'occitan-folk',
    desc: 'Traditional music of Occitania, sung mainly in Occitan and sometimes in French.',
    hard: ['french-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Auvergnat Folk Music',
    id: 'auvergnat-folk',
    desc: 'Traditional Folk Music from Auvergne region.',
    hard: ['occitan-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Gascon Folk Music',
    id: 'gascon-folk',
    desc: 'French Folk Music from the Gascony cultural region in southwest France.',
    hard: ['occitan-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Polifonia occitana',
    id: 'polifonia-occitana',
    desc: 'Polyphonic chant from the Occitan region.',
    hard: ['occitan-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'German Folk Music',
    id: 'german-folk',
    desc: 'Traditional Folk Music of Germany.',
    hard: ['european-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Gstanzl',
    id: 'gstanzl',
    desc: 'Short improvised traditional song form the larger Bavarian region (Southeastern Germany and Austria), satirical and often being accompanied with dances.',
    hard: ['german-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Pennsylvania Dutch Folk Music',
    id: 'pennsylvania-dutch-folk',
    desc: 'Traditional music of the Pennsylvania Dutch.',
    hard: ['german-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Għana',
    id: 'ghana',
    desc: 'Indigenous Maltese folk which consists of quatrains, ideally improvised, following a rhyme scheme of a-b-c-b, and sung to traditional tunes, usually accompanied by guitars.',
    hard: ['european-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Hungarian Folk Music',
    id: 'hungarian-folk',
    desc: 'Traditional Folk Music of the Hungarians.',
    hard: ['european-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Csárdás',
    id: 'csardas',
    desc: 'Traditional Hungarian dance and music form characterized by tempo variations.',
    hard: ['hungarian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Magyar nóta',
    id: 'magyar-nota',
    desc: 'Hungarian genre from the 19th century, combining Hungarian Folk Music with Western Classical Music composition techniques.',
    hard: ['hungarian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Pásztordal',
    id: 'pasztordal',
    desc: 'Sung by men who guard livestock, reflecting on their occupation and social position.',
    hard: ['hungarian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Istrian Folk Music',
    id: 'istrian-folk',
    desc: 'Traditional Folk Music of Istria.',
    hard: ['european-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Italian Folk Music',
    id: 'italian-folk',
    desc: 'Folk traditions of Italy.',
    hard: ['european-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Canzone napoletana',
    id: 'canzone-napoletana',
    desc: 'Sung in the Neapolitan language by a male voice with instrumental accompaniment, originating in the Italian city of Naples and the surrounding regions.',
    hard: ['italian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Liscio',
    id: 'liscio',
    desc: 'Italian popular genre characterized by the fast execution of solo instruments such as clarinet, saxophone, or the accordion.',
    hard: ['italian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Sardinian Folk Music',
    id: 'sardinian-folk',
    desc: 'Traditional Folk Music of Sardinia, an island in the Mediterranean Sea.',
    hard: ['italian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Cantu a chiterra',
    id: 'cantu-a-chiterra',
    desc: 'Traditional monophonic singing accompanied by a chittera sarda from the Mediterranean island of Sardinia.',
    hard: ['sardinian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Cantu a tenore',
    id: 'cantu-a-tenore',
    desc: 'Secular Polyphonic Chant from the Mediterranean island of Sardinia.',
    hard: ['sardinian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Stornello',
    id: 'stornello',
    desc: 'Italian folk poetry, generally improvised and handed down by street singers, carters or sellers.',
    hard: ['italian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Tarantella',
    id: 'tarantella',
    desc: 'Fast upbeat tempo, switching between major and minor modes while gradually increasing in speed.',
    hard: ['italian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Pizzica',
    id: 'pizzica',
    desc: 'Italian Folk dance and music from Apulia, belonging to the family of Tarantella.',
    hard: ['tarantella'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Tammurriata',
    id: 'tammurriata',
    desc: 'Italian folk from Campania, belonging to the family of Tarantella.',
    hard: ['tarantella'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Trallalero',
    id: 'trallalero',
    desc: 'Polyphonic Traditional Folk Music originating in the Ligurian region of Genoa, in northern Italy.',
    hard: ['italian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Luxembourgish Folk Music',
    id: 'luxembourgish-folk',
    desc: 'Traditional folk music of the Luxembourgish people.',
    hard: ['european-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Neo-Medieval Folk',
    id: 'neo-medieval-folk',
    desc: 'Emulates European Folk Music from the Middle Ages, originating in Germany in the 1980s.',
    hard: ['european-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Bardcore',
    id: 'bardcore',
    desc: 'Rearranges contemporary music with an array of acoustic instrumentation to evoke the aesthetic of medieval Europe.',
    hard: ['neo-medieval-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Neo-Pagan Folk',
    id: 'neo-pagan-folk',
    desc: 'Emulates music played by pagan people, particularly from pre-Christian Europe.',
    hard: ['european-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Nordic Folk Music',
    id: 'nordic-folk',
    desc: 'Folk of Nordic countries of Denmark, Finland, Iceland, Norway, and Sweden.',
    hard: ['european-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Danish Folk Music',
    id: 'danish-folk',
    desc: 'Folk of the Danish people.',
    hard: ['nordic-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Faroese Folk Music',
    id: 'faroese-folk',
    desc: 'Traditional Folk Music of the Faroe Islands.',
    hard: ['nordic-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Icelandic Folk Music',
    id: 'icelandic-folk',
    desc: 'Traditional Folk Music of Iceland, including a variety of styles like the rímur, the kvædaskapur and langspil instrumental music.',
    hard: ['nordic-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Joik',
    id: 'joik',
    desc: 'Traditional Sami singing style found in northern Finland, Sweden, Norway and Russia.',
    hard: ['nordic-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Nordic Old Time Dance Music',
    id: 'nordic-old-time-dance',
    desc: 'Meta-genre strongly related to Nordic Folk Music having less complex structures, easy rhythms, and melodic lines.',
    hard: ['nordic-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Polska',
    id: 'polska',
    desc: 'Traditional Nordic dance with a 3/4 rhythm.',
    hard: ['nordic-old-time-dance'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Hambo',
    id: 'hambo',
    desc: 'Traditional Swedish dance with a 3/4 rhythm and an emphasis on the first beat.',
    hard: ['polska'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Norwegian Folk Music',
    id: 'norwegian-folk',
    desc: 'Traditional Folk Music of Norway, primarily intended as accompaniment for dancing and coming in two main varieties, instrumental and vocal music.',
    hard: ['nordic-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Swedish Folk Music',
    id: 'swedish-folk',
    desc: 'Traditional music of the Swedish people, commonly incorporating fiddle, accordion, flute, nyckelharpa, and/or voice.',
    hard: ['nordic-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Polka',
    id: 'polka',
    desc: 'Lively style and corresponding dance originating in Central and Eastern Europe, featuring a 2/4 cut time beat and instruments which vary by region.',
    hard: ['european-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Chicago Polka',
    id: 'chicago-polka',
    desc: 'Polish-American style known for slower tempo, improvisation and the ensemble typically including the clarinet, trumpet, and concertina.',
    hard: ['polka'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Eastern-Style Polka',
    id: 'eastern-style-polka',
    desc: 'Fast, urban Polish-American style performed by a Big Band-like ensemble.',
    hard: ['polka'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Polka peruana',
    id: 'polka-peruana',
    desc: 'Peruvian adaptation of European Polka, blending Afro-Peruvian rhythms and criollo melodies.',
    hard: ['polka'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Portuguese Folk Music',
    id: 'portuguese-folk',
    desc: 'Traditional Folk Music from Portugal.',
    hard: ['european-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Cante alentejano',
    id: 'cante-alentejano',
    desc: 'Traditional Portuguese Music based on vocal music from the Alentejo region.',
    hard: ['portuguese-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Chamarrita açoriana',
    id: 'chamarrita-acoriana',
    desc: 'Refers to a popular folkloric dance, of the Azores islands, as well as the accompanying music.',
    hard: ['portuguese-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Desgarrada',
    id: 'desgarrada',
    desc: 'Improvisational tradition from Northern Portugal where two vocalists address and respond to each other, usually in a joking manner.',
    hard: ['portuguese-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Fado',
    id: 'fado',
    desc: 'Tradition from Portugal originating in the first half of the 19th century, mainly consisting of melancholic songs accompanied by Portuguese guitars or classical guitars.',
    hard: ['portuguese-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Fado de Coimbra',
    id: 'fado-de-coimbra',
    desc: 'Fado variant originated in the city of Coimbra, known for its serenades.',
    hard: ['fado'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Trás-os-Montes Folk Music',
    id: 'tras-os-montes-folk',
    desc: 'Traditional music of the Portuguese province of Trás-os-Montes.',
    hard: ['portuguese-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Vira',
    id: 'vira',
    desc: 'Musical-choreographic genre performed in Portuguese folklore, characteristic of the Minho region.',
    hard: ['portuguese-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Romanian Folk Music',
    id: 'romanian-folk',
    desc: 'Traditional Folk Music of the Romanians.',
    hard: ['european-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Bocet',
    id: 'bocet',
    desc: 'Traditional Romanian music sung by women mourning at a funeral.',
    hard: ['romanian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Colinde',
    id: 'colinde',
    desc: 'Christmas music from Romanian folklore with ritualistic and pagan roots.',
    hard: ['romanian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Doină',
    id: 'doina',
    desc: 'Melancholic, lyrical folk song characterised by its free rhythm.',
    hard: ['romanian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Slavic Folk Music',
    id: 'slavic-folk',
    desc: 'Traditional Folk Music native to Slavic peoples.',
    hard: ['european-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Belarusian Folk Music',
    id: 'belarusian-folk',
    desc: 'Eastern Slavic Folk Music, including traditional ceremonial, wedding, and harvest songs.',
    hard: ['slavic-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Czech Folk Music',
    id: 'czech-folk',
    desc: 'Folk of the Czech people in central Europe.',
    hard: ['slavic-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Goral Music',
    id: 'goral',
    desc: 'Music of highlanders occupying Northern Carpathians (Gorals).',
    hard: ['slavic-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Polish Goral Music',
    id: 'polish-goral',
    desc: 'Music of indigenous highlanders native to the Western Beskids and the Podhale regions in Southern Poland.',
    hard: ['goral'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Moravian Folk Music',
    id: 'moravian-folk',
    desc: 'Traditional Folk Music of the Moravian people.',
    hard: ['slavic-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Polish Folk Music',
    id: 'polish-folk',
    desc: 'Traditional Folk Music of the Poles.',
    hard: ['slavic-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Folklor miejski',
    id: 'folklor-miejski',
    desc: 'Urban folk street band traditions of Polish cities.',
    hard: ['polish-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Warsaw City Folk',
    id: 'warsaw-city-folk',
    desc: 'Traditional urban poetry sung in the Warsaw dialect by buskers, and accompanied by street bands.',
    hard: ['folklor-miejski'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Kashubian Folk Music',
    id: 'kashubian-folk',
    desc: 'Traditional Folk Music of the Kashubian people of northwestern Poland.',
    hard: ['polish-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Krakowiak',
    id: 'krakowiak',
    desc: 'Fast, syncopated, duple-time national dance of Poland.',
    hard: ['polish-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Kujawiak',
    id: 'kujawiak',
    desc: 'Calm, triple-time national dance of Poland.',
    hard: ['polish-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Kujon',
    id: 'kujon',
    desc: 'Melancholic triple-time folk dance from Łowicz and Łęczyca regions, related to Kujawiak and Oberek.',
    hard: ['polish-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Kurpian Folk Music',
    id: 'kurpian-folk',
    desc: 'Traditional Folk Music of the Kurpian people of eastern Poland.',
    hard: ['polish-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Oberek',
    id: 'oberek',
    desc: 'Fastest triple-time national dance of Poland.',
    hard: ['polish-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Russian Folk Music',
    id: 'russian-folk',
    desc: 'Eastern Slavic Folk Music native to the Russian people.',
    hard: ['slavic-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Slovak Folk Music',
    id: 'slovak-folk',
    desc: 'Traditional Folk Music of the Slovaks.',
    hard: ['slavic-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Slovenian Folk Music',
    id: 'slovenian-folk',
    desc: 'Traditional Folk Music of the Slovenian people.',
    hard: ['slavic-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Ukrainian Folk Music',
    id: 'ukrainian-folk',
    desc: 'Traditions of the people of Ukraine.',
    hard: ['slavic-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Duma',
    id: 'duma',
    desc: 'Type of Ukrainian sung epic poem.',
    hard: ['ukrainian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Hutsul Folk Music',
    id: 'hutsul-folk',
    desc: 'Traditional Folk Music of the Hutsul people.',
    hard: ['ukrainian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Spanish Folk Music',
    id: 'spanish-folk',
    desc: 'Traditional Folk Music of Spain, widely diverse due to the distinct culture and traditions of the country\'s different regions.',
    hard: ['european-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Andalusian Folk Music',
    id: 'andalusian-folk',
    desc: 'Flamenco of Andalusia in southern Spain, rooted in traditional music and dances and developed mostly after the 18th century by the Romani people of Andalusia (known locally as gitanos).',
    hard: ['spanish-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Saeta',
    id: 'saeta',
    desc: 'Traditional religious praise song that originated in Andalusia, Spain towards the end of the late Middle Ages.',
    hard: ['andalusian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Sevillanas',
    id: 'sevillanas',
    desc: 'Named after the city of Seville in Spain, typically rhythmic with a 3/4 beat and guitar accompaniment.',
    hard: ['andalusian-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Aragonese Folk Music',
    id: 'aragonese-folk',
    desc: 'Traditional Folk Music of the Aragonese people.',
    hard: ['spanish-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Asturian Folk Music',
    id: 'asturian-folk',
    desc: 'Traditional music of the Asturian people.',
    hard: ['spanish-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Canarian Folk Music',
    id: 'canarian-folk',
    desc: 'Traditional folk of the Canary Islands.',
    hard: ['spanish-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Chotis madrileño',
    id: 'chotis-madrileno',
    desc: 'Spanish variant which developed through the incorporation of regional folk influences and an association with the local castizo culture in Madrid, the capital of Spain.',
    hard: ['spanish-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Copla',
    id: 'copla',
    desc: 'Evolved from Spanish theatrical styles like Cuplé and has strong links to Flamenco.',
    hard: ['spanish-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Cuplé',
    id: 'cuple',
    desc: 'Originally developed in the 19th century as a blend of old theatre Spanish styles based in short monologues (jácara and tonadilla) and French Couplet.',
    hard: ['spanish-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Galician Folk Music',
    id: 'galician-folk',
    desc: 'Traditional music of the Galician people.',
    hard: ['spanish-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Pasodoble',
    id: 'pasodoble',
    desc: 'Mainly instrumental Spanish style primarily associated with bullfighting and popular celebrations, believed to originate from a double-time military march from France in the 18th century.',
    hard: ['spanish-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Valencian Folk Music',
    id: 'valencian-folk',
    desc: 'Traditional music of the Valencian Country.',
    hard: ['spanish-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Volga-Ural Folk Music',
    id: 'volga-ural-folk',
    desc: 'Traditional Folk Music of the Volga-Ural region in the European Russia.',
    hard: ['european-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Bashkir Folk Music',
    id: 'bashkir-folk',
    desc: 'Traditional folk of the Bashkir people, a Turkic ethnic group inhabiting the Republic of Bashkortostan (Bashkiria), a federal subject of the Russian Federation, and its neighboring areas on both sides of the Ural mountains.',
    hard: ['volga-ural-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Chuvash Folk Music',
    id: 'chuvash-folk',
    desc: 'Traditional Folk Music of the Chuvash people.',
    hard: ['volga-ural-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Komi Folk Music',
    id: 'komi-folk',
    desc: 'Traditional Folk Music of the Komi people.',
    hard: ['volga-ural-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Mari Folk Music',
    id: 'mari-folk',
    desc: 'Traditional Folk Music of the Mari people.',
    hard: ['volga-ural-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Mordvin Folk Music',
    id: 'mordvin-folk',
    desc: 'Traditional Folk Music of the Mordvin people.',
    hard: ['volga-ural-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Udmurt Folk Music',
    id: 'udmurt-folk',
    desc: 'Traditional Folk Music of the Udmurt people inhabiting areas in the Volga-Ural region of Russia.',
    hard: ['volga-ural-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Volga Tatar Folk Music',
    id: 'volga-tatar-folk',
    desc: 'Traditional Folk Music of the Volga Tatar people native to republics of Tatarstan and Bashkortostan.',
    hard: ['volga-ural-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Walloon Folk Music',
    id: 'walloon-folk',
    desc: 'Traditional Folk Music of Wallonia, the mostly French-speaking southern region of Belgium which also includes a few Flemish and German minorities.',
    hard: ['european-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'White Voice',
    id: 'white-voice',
    desc: 'Traditional form of vocal music of Eastern European peoples.',
    hard: ['european-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Yiddish Folksong',
    id: 'yiddish-folksong',
    desc: 'Traditional folk developed in Ashkenazi Jewish communities, particularly those of Yiddish-speaking Eastern and Central Europe.',
    hard: ['european-folk'],
    soft: [],
  },
]

const AmericanFolk = [
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'American Folk Music',
    id: 'american-folk',
    desc: 'Traces back through the history of European and West African settlement and migration to North America, including parts of northern Mexico and Canada in addition to the United States.',
    hard: ['traditional-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Appalachian Folk Music',
    id: 'appalachian-folk',
    desc: 'Folk of the Appalachian Mountains in the Eastern United States.',
    hard: ['american-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Old-Time',
    id: 'old-time',
    desc: 'Pre-Bluegrass North American string band styles, particularly those rooted in Appalachian Folk Music.',
    hard: ['appalachian-folk'],
    soft: [],
  },

  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Field Hollers',
    id: 'field-hollers',
    desc: 'Created by African-American slaves working on cotton plantations, featuring expressive vocals to no strict rhythm.',
    hard: ['american-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Fife and Drum Blues',
    id: 'fife-and-drum-blues',
    desc: 'Rooted in martial Fife and Drum Corps music, originated among Afro-American communities in Mississippi.',
    hard: ['american-folk'],
    soft: [],
  },

  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Ring Shout',
    id: 'ring-shout',
    desc: 'Ritual practiced by African-Americans in the US South, characterized by shouting, chanting and people dancing in a circle while praying and clapping.',
    hard: ['american-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Sacred Harp Singing',
    id: 'sacred-harp-singing',
    desc: 'Predominantly 19th-century English hymns with tunes derived from old folk melodies.',
    hard: ['american-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Spirituals',
    id: 'spirituals',
    desc: 'Predecessor to Gospel that began as unaccompanied singing by American slaves; shares some of the characteristics of Work Song.',
    hard: ['american-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Talking Blues',
    id: 'talking-blues',
    desc: 'American Folk Music with spoken or nearly spoken vocals; often features dry humor and social commentary.',
    hard: ['american-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Traditional Black Gospel',
    id: 'traditional-black-gospel',
    desc: 'Born out of Spirituals in the early 20th century with influence from Southern Gospel and Blues, often featuring passionate or energetic vocal performances, motifs of salvation, and testaments of hardship.',
    hard: ['american-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Traditional Cajun Music',
    id: 'traditional-cajun',
    desc: 'Earliest and most "pure" form of Cajun Music, employing basic rhythms and frequent fiddle double stops.',
    hard: ['american-folk'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Traditional Country',
    id: 'traditional-country',
    desc: 'Closely aligned with American Folk Music and Blues roots, from country\'s inception in Appalachia and the American South until the popularity of Honky Tonk and Country Pop in the 1950s.',
    hard: ['american-folk', 'blues'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Close Harmony',
    id: 'close-harmony',
    desc: 'Traditional two-part harmony singing performed mostly by brothers.',
    hard: ['traditional-country'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Country Gospel',
    id: 'country-gospel',
    desc: 'Incorporates the harmonies and Christian themes of Gospel.',
    hard: ['traditional-country'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Bluegrass Gospel',
    id: 'bluegrass-gospel',
    desc: 'Incorporates the religious topics and harmony vocals found in Country Gospel.',
    hard: ['country-gospel', 'traditional-bluegrass'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Country Yodeling',
    id: 'country-yodeling',
    desc: 'Vocal technique of Yodeling, brought to the United States by German settlers, sung over the instrumentation of Traditional Country.',
    hard: ['traditional-country'],
    soft: [],
  },
  {
    type: Type.Sub,
    parent: Type.Sub,
    label: 'Traditional Bluegrass',
    id: 'traditional-bluegrass',
    desc: 'Driving tempos, acoustic stringed instrumentation, and high vocal harmonies, adhering to the stylistic roots of the Bluegrass genre.',
    hard: ['traditional-country'],
    soft: [],
  },
]


export const Folk = [{
  type: Type.Super,
  label: 'Folk',
  id: 'folk',
  desc: 'Roots music from world culture, encompasing international tranditional folk',
  hard: [],
  soft: []
},

{
  type: Type.Genre,
  parent: Type.Super,
  label: 'Folk Rock',
  id: 'folk-rock',
  desc: 'A fusion genre combining elements of folk music and rock music, typically featuring acoustic instruments and lyrical storytelling.',
  hard: ['folk', 'rock'],
  soft: []
},

{
  type: Type.Genre,

  parent: Type.Super,
  label: 'Contemporary Folk',
  id: 'contemporary-folk',
  desc: 'Generally acoustic and modernized traditional folk music',
  hard: ['folk'],
  soft: []
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'American Primitivism',
  id: 'american-primitivism',
  desc: 'Blends avant-garde and neo-classical compositions with traditional Country Blues fingerpicking techniques.',
  hard: ['contemporary-folk'],
  soft: ['avant-garde', 'neo-classical'],
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Anti-Folk',
  id: 'anti-folk',
  desc: 'Rawer approach to folk, with an often self-mocking and sarcastic tone.',
  hard: ['contemporary-folk'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Super,
  label: 'Avant-Folk',
  id: 'avant-folk',
  desc: 'Experimental-influenced and playing with instrumentation, rhythm, and other factors not commonly found in folk.',
  hard: ['folk', 'avant-garde'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Free Folk',
  id: 'free-folk',
  desc: 'Incorporates improvisation, repetition and extended song lengths.',
  hard: ['avant-folk'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Campus Folk',
  id: 'campus-folk',
  desc: 'Born in Taiwan in the mid-1970s, this movement originated with university students creating their own modern-style songs in the wake of international tensions like Taiwan’s isolation from the United Nations and the United States’ embrace of the PRC as a diplomatic partner.',
  hard: ['contemporary-folk'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Chamber Folk',
  id: 'chamber-folk',
  desc: 'Gentle fingerpicked acoustic guitar or harp-led music that commonly includes a backing ensemble of harpsichords, strings, horns, or other orchestral instruments.',
  hard: ['contemporary-folk', 'chamber-music'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Country Folk',
  id: 'country-folk',
  desc: 'Emphasises Traditional Country instrumentation as well as influences from contemporary Singer-Songwriter traditions, such as a gentler disposition and prominent lyrical storytelling focus.',
  hard: ['contemporary-folk', 'country'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Folk Baroque',
  id: 'folk-baroque',
  desc: 'Originated in England in the early 1960s, featuring a distinctive guitar fingerpicking style of the same name and the DADGAD guitar tuning.',
  hard: ['contemporary-folk'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Folk Pop',
  id: 'folk-pop',
  desc: 'Blends Contemporary Folk with a Pop sensibility, most popular in the late 1960s and early 1970s and featuring influence from the contemporary Folk Rock style.',
  hard: ['contemporary-folk', 'pop'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Stomp and Holler',
  id: 'stomp-and-holler',
  desc: 'Highlights driving "stomping" rhythms and shouted group vocal harmonies, often drawing influences from Pop Rock, Indie Folk, and other genres, while maintaining a characteristically mellow and commercial sound.',
  hard: ['folk-pop'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Indie Folk',
  id: 'indie-folk',
  desc: 'Combines the melodic sensibilities and production style of Indie Rock and Indie Pop with acoustic instrumentation and influences from Folk, Singer-Songwriter, and sometimes Country.',
  hard: ['contemporary-folk', 'indie-rock', 'indie-pop'],
  soft: ['country', 'singer-songwriter'],
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Neofolk',
  id: 'neofolk',
  desc: 'Emerged in the mid-1980s from the Post-Industrial scene, with a dark, often martial atmosphere.',
  hard: ['contemporary-folk', 'post-industrial'],
  soft: ['martial-industrial'],
  bands: 'swans, sol invictus'
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Dark Folk',
  id: 'dark-folk',
  desc: 'Minimalistic and melancholic sound with influence from Nordic Folk Music and even Ambient.',
  hard: ['neofolk', 'nordic-folk-music'],
  soft: ['ambient'],
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Neofolklore',
  id: 'neofolklore',
  desc: 'Short-lived movement that reincorporated traditional Chilean folklore into modern production and styling inspired by foreign musicians.',
  hard: ['contemporary-folk'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Progressive Folk',
  id: 'progressive-folk',
  desc: 'Draws from a variety of sources to subvert traditional acoustic song forms, with diversity ranging from Jazz to Medieval music to various Regional Music traditions.',
  hard: ['contemporary-folk'],
  soft: ['folk', 'medieval', 'regional-music'],
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Psychedelic Folk',
  id: 'psychedelic-folk',
  desc: 'Acoustic forms that capture an atmosphere that is at turns dream-like, "spaced-out", whimsical, haunting, mystical, and melancholic.',
  hard: ['contemporary-folk'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Freak Folk',
  id: 'freak-folk',
  desc: 'Offshoot of the New Weird America movement characterised by acoustic and eclectic instruments, peculiar vocal styles, romantic lyrics, and a childlike atmosphere.',
  hard: ['psychedelic-folk'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Udigrudi',
  id: 'udigrudi',
  desc: 'Movement that emerged in the Brazilian city of Recife during the 1970s that combines psychedelic elements with music of Northeastern Brazil.',
  hard: ['psychedelic-folk', 'brazilian-music'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Wyrd Folk',
  id: 'wyrd-folk',
  desc: 'Closely tied to mysticism, old folk beliefs, and Folk Horror; often described as "witchy" or "pagan."',
  hard: ['psychedelic-folk'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Skiffle',
  id: 'skiffle',
  desc: 'Grew out of British Dixieland trad jazz, drawing influence from 1920s Jug Bands and the strong rhythms of 1950s Honky Tonk and Rock & Roll.',
  hard: ['contemporary-folk', 'jug-band'],
  soft: ['folk'],
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Xinyao',
  id: 'xinyao',
  desc: 'Singaporean Mandarin-language style, generally featuring harmonised group vocals and backed mainly by acoustic guitar.',
  hard: ['contemporary-folk'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Traditional Folk Music',
  id: 'traditional-folk',
  desc: 'Singaporean Mandarin-language style, generally featuring harmonised group vocals and backed mainly by acoustic guitar.',
  hard: ['contemporary-folk'],
  soft: [],
},
...AfricanFolk,
...ArabicFolk,
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Australian Folk Music',
  id: 'australian-folk',
  desc: 'Folk traditions of the European colonists and convicts in Australia.',
  hard: ['contemporary-folk'],
  soft: [],
},
...BrasilianFolk,
...CanadianFolk,
...CaucasianFolk,
...EastAsianFolk,
...EuropeanFolk,
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Drinking Songs',
  id: 'drinking-songs',
  desc: 'Songs performed at social gatherings, often with themes of celebration and camaraderie.',
  hard: ['contemporary-folk'],
  soft: [],
},

...AmericanFolk,
...Blues,
{
  type: Type.Scene,
  parent: Type.Super,
  label: 'Protest Music',
  desc: 'Scene that recollects all music connected to protest about social issues and political topics.',
  id: 'Protest-music',
  hard: ['folk', 'roots-regae', 'conscious-hiphop', 'punk', 'work-music', 'crust-punk', 'anarcho-punk'],
  soft: []
},
]
