
export enum Type {
  'Super' = 1,
  'Genre' = 2,
  'Sub' = 3,
  'Scene' = 4,
  'Fusion' = 5
}

const Blues = [
  {
  type: Type.Genre,
  parent: Type.Super,
  label: 'Blues',
  id: 'blues',
  desc: 'Originated toward the end of the 19th century in African American communities in the United States, particularly the Deep South; drew on traditional Spirituals and Work Song; highly influential to the whole of Western popular music, Mostly using electric guitars nowadays.',
  hard: ['folk', 'rock'],
  soft: ['work-music']
},

{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Acoustic Blues',
  id: 'acoustic-blues',
  desc: 'Developed as a king of more spiritual work and blues song, prominent as an early form of blues',
  hard: ['blues'],
  soft: []
},

{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Acoustic Chicago Blues',
  id: 'acoustic-chicago-blues',
  desc: 'Unplugged Blues made in the Chicago region, primarily during the 1930s and 1940s.',
  hard: ['acoustic-blues'],
  dates: '1930s',
  soft: []
},

{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Acoustic Texas Blues',
  id: 'acoustic-texas-blues',
  desc: 'Laid-back swing rhythms and guitar ornamentation, including solos.',
  hard: ['acoustic-blues', 'country-blues'],
  dates: '',
  soft: []
},

{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Jug Band',
  id: 'jug-band',
  desc: 'Usually features a jug as the bass instrument as well as other homemade (or easily affordable) instruments, such as kazoos and washboards.',
  hard: ['acoustic-blues'],
  dates: '',
  soft: []
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Piedmont Blues',
  id: 'piedmont-blues',
  desc: 'Developed in the early 20th century in the southern Appalachian foothills and characterized by a syncopated but melodic Ragtime-based finger-picking acoustic guitar style.',
  hard: ['acoustic-blues', 'country-blues'],
  dates: '',
  soft: []
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Boogie Woogie',
  id: 'boogie-woogie',
  desc: 'Early, upbeat form of blues, characterized by a strong rhythm played on the piano, often with a walking bass line.',
  hard: ['blues'],
  dates: '',
  soft: []
},

{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Country Blues',
  id: 'country-blues',
  desc: 'Various styles of Blues originating in the rural US South, typically relying on expressive vocal delivery and featuring simple, usually acoustic instrumentation.',
  hard: ['blues', 'country'],
  dates: '',
  soft: []
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Delta Blues',
  id: 'delta-blues',
  desc: 'One of the earliest forms of Blues, named for the Mississippi Delta region of the United States where it developed, with a highly rhythmic style and a typical 12-bar structure.',
  hard: ['country-blues'],
  dates: '',
  soft: []
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Hill country Blues',
  id: 'hill-country-blues',
  desc: 'Emphasizes a steady hypnotic groove, sparse percussive and highly energetic guitar riffs, and often features meandering structures with unconventional and usually fewer chord changes compared to Delta Blues.',
  hard: ['country-blues'],
  dates: '',
  soft: []
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Electric Blues',
  id: 'electric-blues',
  desc: 'This genre emerged in the 1940s and 1950s, characterized by the use of electric guitars, harmonicas, and a strong rhythm section, often with a more aggressive sound than traditional acoustic blues.',
  hard: ['blues'],
  dates: '1940s',
  soft: []
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'British Blues',
  id: 'british-blues',
  desc: 'Heavily influenced by the burgeoning United States Blues scene, particularly Chicago Blues.',
  hard: ['electric-blues'],
  dates: '',
  soft: []
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Chicago Blues',
  id: 'chicago-blues',
  desc: 'Heavily inspired by old-time rural blues, transferring it into a small band setup, while maintaining the rough and gritty edges of its ancestry.',
  hard: ['electric-blues'],
  dates: '',
  soft: []
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Electric Texas Blues',
  id: 'electric-texas-blues',
  desc: 'Originating in (but not limited to) Texas; includes Jazz influences like Swing rhythms and sometimes the addition of a horn section.',
  hard: ['electric-blues'],
  dates: '',
  soft: []
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Swamp Blues',
  id: 'swamp-blues',
  desc: 'Originated in Baton Rouge, Louisiana in the 1950s, with a laid-back and relaxed sound that takes influence from Zydeco and Cajun Music.',
  hard: ['electric-blues'],
  dates: '',
  soft: []
},
  {
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Fife and Drum Blues',
  id: 'fife-dnb-blues',
  desc: 'Rooted in martial Fife and Drum Corps music, originated among Afro-American communities in Mississippi.',
  hard: ['blues'],
  dates: '',
  soft: []
},
    {
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Jump Blues',
  id: 'jump-blues',
  desc: 'Emerged in the late 1930s with influence from Jazz styles such as Swing and Big Band, featuring fast tempos and raucous performances.',
  hard: ['blues'],
  dates: '1930s',
  soft: ['jazz', 'swing', 'big-band']
},
     {
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Piano Blues',
  id: 'piano-blues',
  desc: 'Blues music that prominently features the piano as the lead instrument, often incorporating elements of boogie-woogie and stride piano styles with a slower tempo',
  hard: ['blues'],
  dates: '',
  soft: ['jazz', 'swing', 'big-band']
},
     {
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Soul Blues',
  id: 'soul-blues',
  desc: 'Combined with soul incorporates with elements of gospel music, characterized by emotive vocals and a strong emphasis on melody and groove.',
  hard: ['blues', 'soul'],
  dates: '',
  soft: []
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Vaudeville Blues',
  id: 'vaudeville-blues',
  desc: 'Blues with vaudeville and theatrical influences.',
  hard: ['blues'],
  soft: []
}
]

export const Folk = [{
  type: Type.Super,
  label: 'Folk',
  id: 'folk',
  desc: 'Roots music from world culture, encompasing international tranditional folk',
  hard: [],
  soft: []
},

{
  type: Type.Genre,
  parent: Type.Super,
  label: 'Folk Rock',
  id: 'folk-rock',
  desc: 'A fusion genre combining elements of folk music and rock music, typically featuring acoustic instruments and lyrical storytelling.',
  hard: ['folk', 'rock'],
  soft: []
}, 
  
{
  type: Type.Genre,

  parent: Type.Super,
  label: 'Contemporary Folk',
  id: 'contemporary-folk',
  desc: 'Generally acoustic and modernized traditional folk music',
  hard: ['folk'],
  soft: []
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'American Primitivism',
  id: 'american-primitivism',
  desc: 'Blends avant-garde and neo-classical compositions with traditional Country Blues fingerpicking techniques.',
  hard: ['contemporary-folk'],
  soft: ['avant-garde', 'neo-classical'],
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Anti-Folk',
  id: 'anti-folk',
  desc: 'Rawer approach to folk, with an often self-mocking and sarcastic tone.',
  hard: ['contemporary-folk'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Super,
  label: 'Avant-Folk',
  id: 'avant-folk',
  desc: 'Experimental-influenced and playing with instrumentation, rhythm, and other factors not commonly found in folk.',
  hard: ['folk', 'avant-garde'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Free Folk',
  id: 'free-folk',
  desc: 'Incorporates improvisation, repetition and extended song lengths.',
  hard: ['avant-folk'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Campus Folk',
  id: 'campus-folk',
  desc: 'Born in Taiwan in the mid-1970s, this movement originated with university students creating their own modern-style songs in the wake of international tensions like Taiwan’s isolation from the United Nations and the United States’ embrace of the PRC as a diplomatic partner.',
  hard: ['contemporary-folk'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Chamber Folk',
  id: 'chamber-folk',
  desc: 'Gentle fingerpicked acoustic guitar or harp-led music that commonly includes a backing ensemble of harpsichords, strings, horns, or other orchestral instruments.',
  hard: ['contemporary-folk', 'chamber-music'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Country Folk',
  id: 'country-folk',
  desc: 'Emphasises Traditional Country instrumentation as well as influences from contemporary Singer-Songwriter traditions, such as a gentler disposition and prominent lyrical storytelling focus.',
  hard: ['contemporary-folk','country'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Folk Baroque',
  id: 'folk-baroque',
  desc: 'Originated in England in the early 1960s, featuring a distinctive guitar fingerpicking style of the same name and the DADGAD guitar tuning.',
  hard: ['contemporary-folk'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Folk Pop',
  id: 'folk-pop',
  desc: 'Blends Contemporary Folk with a Pop sensibility, most popular in the late 1960s and early 1970s and featuring influence from the contemporary Folk Rock style.',
  hard: ['contemporary-folk', 'pop'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Stomp and Holler',
  id: 'stomp-and-holler',
  desc: 'Highlights driving "stomping" rhythms and shouted group vocal harmonies, often drawing influences from Pop Rock, Indie Folk, and other genres, while maintaining a characteristically mellow and commercial sound.',
  hard: ['folk-pop'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Indie Folk',
  id: 'indie-folk',
  desc: 'Combines the melodic sensibilities and production style of Indie Rock and Indie Pop with acoustic instrumentation and influences from Folk, Singer-Songwriter, and sometimes Country.',
  hard: ['contemporary-folk','indie-rock', 'indie-pop'],
  soft: ['country', 'singer-songwriter'],
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Neofolk',
  id: 'neofolk',
  desc: 'Emerged in the mid-1980s from the Post-Industrial scene, with a dark, often martial atmosphere.',
  hard: ['contemporary-folk','post-industrial'],
  soft: ['martial-industrial'],
  bands: 'swans, sol invictus'
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Dark Folk',
  id: 'dark-folk',
  desc: 'Minimalistic and melancholic sound with influence from Nordic Folk Music and even Ambient.',
  hard: ['neofolk', 'nordic-folk-music'],
  soft: ['ambient'],
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Neofolklore',
  id: 'neofolklore',
  desc: 'Short-lived movement that reincorporated traditional Chilean folklore into modern production and styling inspired by foreign musicians.',
  hard: ['contemporary-folk'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Progressive Folk',
  id: 'progressive-folk',
  desc: 'Draws from a variety of sources to subvert traditional acoustic song forms, with diversity ranging from Jazz to Medieval music to various Regional Music traditions.',
  hard: ['contemporary-folk'],
  soft: ['folk', 'medieval', 'regional-music'],
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Psychedelic Folk',
  id: 'psychedelic-folk',
  desc: 'Acoustic forms that capture an atmosphere that is at turns dream-like, "spaced-out", whimsical, haunting, mystical, and melancholic.',
  hard: ['contemporary-folk'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Freak Folk',
  id: 'freak-folk',
  desc: 'Offshoot of the New Weird America movement characterised by acoustic and eclectic instruments, peculiar vocal styles, romantic lyrics, and a childlike atmosphere.',
  hard: ['psychedelic-folk'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Udigrudi',
  id: 'udigrudi',
  desc: 'Movement that emerged in the Brazilian city of Recife during the 1970s that combines psychedelic elements with music of Northeastern Brazil.',
  hard: ['psychedelic-folk', 'brazilian-music'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Wyrd Folk',
  id: 'wyrd-folk',
  desc: 'Closely tied to mysticism, old folk beliefs, and Folk Horror; often described as "witchy" or "pagan."',
  hard: ['psychedelic-folk'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Skiffle',
  id: 'skiffle',
  desc: 'Grew out of British Dixieland trad jazz, drawing influence from 1920s Jug Bands and the strong rhythms of 1950s Honky Tonk and Rock & Roll.',
  hard: ['contemporary-folk','jug-band'],
  soft: ['folk'],
},
{
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Xinyao',
  id: 'xinyao',
  desc: 'Singaporean Mandarin-language style, generally featuring harmonised group vocals and backed mainly by acoustic guitar.',
  hard: ['contemporary-folk'],
  soft: [],
},
  {
  type: Type.Sub,
  parent: Type.Genre,
  label: 'Traditional Folk Music',
  id: 'traditional-folk',
  desc: 'Singaporean Mandarin-language style, generally featuring harmonised group vocals and backed mainly by acoustic guitar.',
  hard: ['contemporary-folk'],
  soft: [],
},
    {
  type: Type.Sub,
  parent: Type.Genre,
  label: 'African Folk Music',
  id: 'african-folk',
  desc: 'Indigenous music of Africa that is passed down orally from generation to generation, the authors of the songs are usually unknown.',
  hard: ['contemporary-folk'],
  soft: [],
},
     {
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Ambasse bey',
  id: 'ambasse-bey',
  desc: 'Indigenous music of Africa that is passed down orally from generation to generation, the authors of the songs are usually unknown.',
  hard: ['african-folk'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Apala',
  id: 'apala',
  desc: 'Yoruba Music developed by Muslims during the late 1930s and early 1940s in the Ijebu region of Yorubaland, the current Ogun state.',
  hard: ['african-folk'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Batuque',
  id: 'batuque',
  desc: "Tradition from Cape Verde, unusual among the islands' music due to its lack of polyphonic singing and its usage of polyrhythms.",
  hard: ['african-folk'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Dagomba Music',
  id: 'dagomba-music',
  desc: 'Music of the Dagomba people of northern Ghana.',
  hard: ['african-folk'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Gnawa',
  id: 'gnawa',
  desc: 'Mixture of Sub-Saharan African, Arabic, and Amazigh Music, created by the Gnawa, an ethnic minority group in North Africa, mainly Morocco.',
  hard: ['african-folk'],
  soft: ['arabic-music', 'amazigh-music'],
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Kabye Folk Music',
  id: 'kabye-folk-music',
  desc: 'Traditional Folk Music of the Kabye people of northern Togo, including some of the most singular styles that can be found in West Africa.',
  hard: ['african-folk'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Kilapanga',
  id: 'kilapanga',
  desc: 'Tradition of the Bakongo people from Angola and Congo that has influenced contemporary styles such as Kuduro.',
  hard: ['african-folk'],
  soft: ['kuduro'],
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Malagasy Folk Music',
  id: 'malagasy-folk-music',
  desc: 'Melodic, chordophone-dominated sound; based on the Austronesian Music of the first settlers that arrived on the island from Borneo.',
  hard: ['african-folk'],
  soft: ['austronesian-music'],
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Mbenga-Mbuti Music',
  id: 'mbenga-mbuti-music',
  desc: 'Music of the Mbenga and Mbuti people, Pygmy ethnic groups in Central Africa.',
  hard: ['african-folk'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Moutya',
  id: 'moutya',
  desc: 'Tradition that originated in Seychelles among Creole slaves, similar to Séga, although rawer and played only on large flat drums made from goatskin.',
  hard: ['african-folk'],
  soft: ['sega'],
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Ngoma',
  id: 'ngoma',
  desc: 'Played in Swahili-speaking African countries; primarily focused on rhythm.',
  hard: ['african-folk'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Unyago',
  id: 'unyago',
  desc: 'Traditional music from Zanzibar, traditionally played at womens initiation rituals and weddings.',
  hard: ['ngoma'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Southern African Folk',
  id: 'southern-african-folk',
  desc: 'Traditional Folk Music of southern Africa.',
  hard: ['african-folk'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Afrikaner Folk',
  id: 'afrikaner-folk',
  desc: 'Musical traditions developed by the Afrikaner community in southern Africa.',
  hard: ['southern-african-folk'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Khoisan Folk ',
  id: 'khoisan-folk',
  desc: 'Encompasses traditions of the Khoisan ethnic family groups.',
  hard: ['southern-african-folk'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Nguni Folk',
  id: 'nguni-folk',
  desc: 'Traditions of the Nguni ethnic family groups, a southern Bantu ethnicity.',
  hard: ['southern-african-folk'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Sotho-Tswana Folk',
  id: 'sotho-tswana-folk',
  desc: 'Traditional Folk Music of the Sotho-Tswana ethnic family groups from southern Africa.',
  hard: ['southern-african-folk'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Tchinkoume',
  id: 'tchinkoume',
  desc: 'Tradition from the central region of Benin around Savalou, played with water percussion.',
  hard: ['african-folk'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Traditional Maloya',
  id: 'traditional-maloya',
  desc: 'Derived from Traditional Séga, this is the original dance music of La Réunion.',
  hard: ['african-folk'],
  soft: ['traditional-sega'],
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Traditional Séga',
  id: 'traditional-sega',
  desc: 'Séga dance music born in the 18th century, before its later adoption of Western pop elements.',
  hard: ['african-folk'],
  soft: [],
},
{
  type: Type.Sub,
  parent: Type.Sub,
  label: 'Zinli',
  id: 'zinli',
  desc: 'Traditional rhythmic chanting and percussion adapted to multiple West African contexts in the 20th century.',
  hard: ['african-folk'],
  soft: [],
},
...Blues,
{
  type: Type.Scene,
  parent: Type.Super,
  label: 'Protest Music',
  desc: 'Scene that recollects all music connected to protest about social issues and political topics.',
  id: 'Protest-music',
  hard: ['folk', 'roots-regae', 'conscious-hiphop', 'punk', 'work-music', 'crust-punk', 'anarcho-punk'],
  soft: []
},
]
