
export enum Type {
    'Super' = 1,
    'Genre' = 2,
    'Sub' = 3,
    'Scene' = 4,
    'Fusion' = 5
}

export const HipHop = [
    {
        type: Type.Super,
        label: 'Hip hop',
        desc: 'also known as rap, summarizes the genre of rhytmical poetry singing known as rapping as the movement and the melody and use of electronics which gave foot to their specific sound.',
        id: 'hiphop',
        hard: [],
        soft: ['poetry'],
        dates: '1970s',
        bands:'Kendrick Lamar, Tupac, Mos Def, Nas'
    },
    {
        type: Type.Sub,
        label: 'Abstract Hip hop',
        parent: Type.Super,
        desc: 'Uses much more abstract lyricism than what is considered conventional within the genre, typically through use of metaphors, symbolism, and cryptic meanings.',
        id: 'abstract-hiphop',
        hard: ['hiphop'],
        soft: [],
        bands: 'Madvillain, Deltron 3030'
    },
    {
        type: Type.Sub,
        parent: Type.Super,

        label: 'Afroswing',
        desc: 'Emerged in the United Kingdom during the mid-2010s, incorporating influences from Dancehall, Afrobeats, Contemporary R&B, and a variety of West African Music.',
        id: 'afroswing',
        hard: ['hiphop', 'dancehall', 'rnb'],
        soft: ['world-music']
    },
    {
        type: Type.Sub,
        parent: Type.Super,

        label: 'Afro Trap',
        desc: 'Centered mostly in France, features production influenced by modern styles developed in West and Central Africa with Trap-styled vocal flows.',
        id: 'afro-trap',
        hard: ['hiphop'],
        soft: ['trap']
    },
    {
        type: Type.Sub,
        parent: Type.Super,

        label: 'Arabesque Rap',
        desc: 'merged from Turkey in the late 2000s, based almost exclusively around Arabesk samples and featuring aggressive rap vocals.',
        id: 'arabesque-rap',
        hard: ['hiphop'],
        soft: ['trap']
    },
    {
        type: Type.Sub,
        parent: Type.Super,
        label: 'Bongo Flava',
        desc: 'Tanzanian genre originating in the mid-1990s in the Dar es Salaam area, combining the influence of Rhythm & Blues, Afrobeat, and Dancehall with native Tanzanian styles like Taarab and Muziki wa dansi.',
        id: 'bongo-flava',
        hard: ['hiphop'],
        soft: []
    },
    {
        type: Type.Sub,
        parent: Type.Super,
        label: 'Boom Bap',
        desc: 'Production style identified by an acoustic-sounding drum pattern of a kick drum on the downbeat followed by a cracking snare on the upbeat.',
        id: 'boom-bap',
        hard: ['hiphop'],
        soft: []
    },
    {
        type: Type.Sub,
        parent: Type.Super,
        label: 'Bounce',
        id: 'bounce',
        desc: 'Developed in New Orleans in the early 1990s, initially defined by a slow to midtempo beat with a double-time hi-hat on top.',
        hard: ['hiphop'],
        soft: []
    },
    {
        type: Type.Sub,
        parent: Type.Super,
        label: 'Chipmunk Soul',
        id: 'chipmunk-soul',
        desc: 'Sped-up vocal samples and slick, soulful production.',
        hard: ['hiphop'],
        soft: []
    },
    {
        type: Type.Genre,
        parent: Type.Super,
        label: 'Chopped and Screwed',
        id: 'choppednscrewed',
        desc: 'Remixing technique that consists of skipping effects ("chopping") and dropping the tempo ("screwing").',
        hard: ['hiphop' , 'electronics'],
        soft: []
    },
    {
        type: Type.Sub,
        parent: Type.Super,
        label: 'Christian Hip Hop',
        id: 'christian-hiphop',
        desc: 'Employs lyrics with a pro-Christianity message to profess the performers faith, often to attract attention from new potential converts.',
        hard: ['hiphop' ],
        soft: []
    },
    {
        type: Type.Sub,
        parent: Type.Super,
        label: 'Cloud Rap',
        id: 'cloud-rap',
        desc: 'Emerged in the early 2010s, known for its relaxed, dream-like, and reverb-heavy production style, taking influence from Chillwave, and producers obscure sample choices.',
        hard: ['hiphop', 'chillwave' ],
        soft: []
    },
    {
        type: Type.Sub,
        parent: Type.Super,
        label: 'Comedy Rap',
        id: 'comedy-rap',
        desc: 'Primarily intended to be humorous, through the use of comedic lyrics, production, delivery, or other musical aspects.',
        hard: ['hiphop' ],
        soft: []
    },
    {
        type: Type.Sub,
        parent: Type.Sub,
        label: 'Chad Hop',
        id: 'chad-hop',
        desc: 'Satirises British cultural stereotypes with posh rapping and a distinctive retro aesthetic drawn from steampunk subcultures, often with elements of Music Hall.',
        hard: ['comedy-rap' ],
        soft: []
    },
    {
        type: Type.Sub,
        parent: Type.Super,
        label: 'Conscious Hip hop',
        id: 'conscious-hiphop',
        desc: 'Artists whose lyrics deal with social issues.',
        hard: ['hiphop' ],
        soft: [],
        bands: 'mos def, little simz'
    },
    {
        type: Type.Sub,
        parent: Type.Super,
        label: 'Crunk',
        id: 'crunk',
        desc: 'Originating from the southern United States and reliant on drum machines and synthesizer stabs to create an energetic, often dance-oriented sound.',
        hard: ['hiphop' ],
        soft: [],
        bands: 'Three 6 mafia'
    },
    {
        type: Type.Sub,
        parent: Type.Sub,
        label: 'Crunkcore',
        id: 'crunkcore',
        desc: 'Combines rapping, screaming and autotune with synthesizers and Hip Hop beats often influenced by Crunk.',
        hard: ['crunk' ],
        soft: [],
    },

    {
        type: Type.Sub,
        parent: Type.Super,
        label: 'Dirty South',
        id: 'dirty-south',
        desc: 'Originated in the Southern US during the mid-1990s, defined by a bouncy rhythm, fast-tempo snares, 808s, heavy bass, and often rapped in a rhythmic delivery consisting of explicit lyrics.',
        hard: ['hiphop' ],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Super,
        label: 'Drumless',
        id: 'drumless',
        desc: 'Stripped-down production style pioneered in the early 2010s and identified by a lack of drums or minimal, subtle percussion left untouched from the original sample or filtered out.',
        hard: ['hiphop' ],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Super,
        label: 'Emo Rap',
        id: 'emo-rap',
        desc: 'Moody, melancholic production combining atmospheric Cloud Rap, and Trap typical drum programming, with sampling from Alternative Rock, Midwest Emo, Emo-Pop, and Pop Punk',
        hard: ['hiphop' ],
        soft: ['cloud-rap', 'emo', 'midwest-emo'],
    },
    {
        type: Type.Genre,
        parent: Type.Super,
        label: 'Experimental Hip hop',
        id: 'experimental-hiphop',
        desc: 'Incorporates experimental and eccentric elements considered unconventional or unorthodox compared to more traditional hip hop.',
        hard: ['hiphop' ],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Super,
        label: 'Industrial Hip hop',
        id: 'industrial-hiphop',
        desc: 'Incorporates harsh elements inspired by Industrial music such as blaring, noisy synths, distorted and metallic percussion, as well as more aggressive and off-kilter rapping styles.',
        hard: ['hiphop', 'industrial' ],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Super,
        label: 'Genge',
        id: 'genge',
        desc: 'Combines elements of Dancehall with various traditions of Kenya',
        hard: ['hiphop', 'dancehall' ],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Sub,
        label: 'Gengetone',
        id: 'gengetone',
        desc: 'Takes strong influence from Reggaetón and modern Dancehall, featuring more explicit lyrics and harder beats.',
        hard: ['genge', 'reggaeton' ],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Super,
        label: 'G-Funk',
        id: 'g-funk',
        desc: 'Relaxed and organic sound featuring live instrumentation, use of P-Funk samples, and high-pitched synth lines.',
        hard: ['hiphop', 'p-funk' ],
        soft: [],
    },
    {
        type: Type.Genre,
        parent: Type.Super,
        label: 'Hardcore Hip hop',
        id: 'hardcore-hiphop',
        desc: 'Confrontation and aggression, whether in the lyricism, vocal delivery, hard beats, heavy production, or any combination thereof.',
        hard: ['hiphop' ],
        soft: [],
        bands: 'Nas, Danny Brown, Public Enemy, Tech n9ne, Canserbero, Run the Jewels'
    },
    {
        type: Type.Sub,
        parent: Type.Genre,
        label: 'Britcore',
        id: 'britcore',
        desc: 'Confrontation and aggression, whether in the lyricism, vocal delivery, hard beats, heavy production, or any combination thereof.',
        hard: ['hardcore-hiphop' ],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Genre,
        label: 'Gangsta rap',
        id: 'gangsta-rap',
        desc: 'Lyrics from a gangster\'s perspective.',
        hard: ['hardcore-hiphop' ],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Sub,
        label: 'Scam rap',
        id: 'scam-rap',
        desc: 'Lyrics from a gangster\'s perspective.',
        hard: ['gangsta-rap' ],
        soft: [],
    },
    {
        type: Type.Genre,
        parent: Type.Genre,
        label: 'Horrorcore',
        id: 'horrorcore',
        desc: 'Lyrical and aesthetic focus on the macabre and morbid, with production generally of a darker nature than is typically found in other Hip Hop.',
        hard: ['hardcore-hiphop' ],
        soft: [],
        bands: 'eminem, clipping, tech n9ne'
    },
    {
        type: Type.Genre,
        parent: Type.Genre,
        label: 'Memphis Rap',
        id: 'memphis-rap',
        desc: 'Minimalistic half-time drum machine programming with droning bass, often paired with aggressive rapping and a double time flow.',
        hard: ['hardcore-hiphop' ],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Genre,
        label: 'Dungeon Rap',
        id: 'dungeon-rap',
        desc: 'Combines the dark production of Memphis Rap with the fantasy aesthetics and sound design of Dungeon Synth.',
        hard: ['memphis-rap', 'dungeon-synth' ],
        soft: [],
    },
    {
        type: Type.Genre,
        parent: Type.Genre,
        label: 'Phonk',
        id: 'phonk',
        desc: 'Modernized, eclectic take on classic Memphis Rap production, featuring various influences from other Hip Hop genres, especially drum programming inspired by other Southern Hip Hop as well as frequent jazzy, funky elements somewhat akin to West Coast Hip Hop and from Electronic music.',
        hard: ['memphis-rap', 'electronics' ],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Genre,
        label: 'Rare Phonk',
        id: 'rare-phonk',
        desc: 'Primarily features eclectic sampling and lush, jazzy beats, usually set to Trap rhythms with prominent influences of Memphis Rap.',
        hard: ['phonk','memphis-rap' ],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Genre,
        label: 'Mid-School hip hop',
        id: 'mid-school-hiphop',
        desc: 'Based around heavy, stripped-down drum machine beats.',
        hard: ['hardcore-hiphop' ],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Super,
        label: 'Hyphy',
        id: 'hyphy',
        desc: 'Party-focused style with upbeat tempos, heavy bass and prominent synths, all underpinned by a distinctive West Coast-style rhythm, claps on beats 2 and 4, and a strong kick drum on beats 1, 2, and either 3 or 4.',
        hard: ['hiphop' ],
        soft: [],
    },
    {
        type: Type.Genre,
        parent: Type.Super,
        label: 'Instrumental Hip hop',
        id: 'instrumental-hiphop',
        desc: 'Can take the form of instrumental versions of songs that normally feature rapping, or hip hop originally released and always intended to be instrumental.',
        hard: ['hiphop' ],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Super,
        label: 'Jerk',
        id: 'jerk',
        desc: 'Sparse, snare-heavy drum patterns loosely inspired by Jerk Rap, which take major elements from other prominent 2010s and 2020s underground hip hop genres like Plugg.',
        hard: ['hiphop' ],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Super,
        label: 'Jersey Club Rap',
        id: 'jersey-club-rap',
        desc: 'Incorporates Jersey Club&#39;s distinct kick-heavy rhythms, which are modified to better suit rapping, featuring less sampling and more atmospheric production than earlier Jersey club.',
        hard: ['hiphop', 'jersey-club' ],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Super,
        label: 'Jersey Drill',
        id: 'jersey-drill',
        desc: 'Mixes Drill and Jersey Club production, characterized by an energetic sound and distinct syncopated rhythms.',
        hard: ['hiphop','drill' ],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Super,
        label: 'Jigg',
        id: 'jigg',
        desc: 'Club-oriented genre characterized by heavy 808-driven beats, imposing synthesized brasses and an uptempo rhythm.',
        hard: ['hiphop'],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Super,
        label: 'Jook',
        id: 'jook',
        desc: 'Fast-paced; draws influence from Bounce, Miami Bass, Jersey Club and Dancehall.',
        hard: ['hiphop'],
        soft: ['bounce', 'miami-bass', 'jersey-club', 'dancehall'],
    },
    {
        type: Type.Sub,
        parent: Type.Super,
        label: 'Latin Rap',
        id: 'latin-rap',
        desc: 'Primarily done in Spanish; incorporates Hispanic American Music elements into its sound.',
        hard: ['hiphop'],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Sub,
        label: 'Chicano Rap',
        id: 'chicano-rap',
        desc: 'Latin Rap with a Mexican twist.',
        hard: ['latin-rap'],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Super,
        label: 'Lo-fi Hip hop',
        id: 'lo-fi-hiphop',
        desc: 'Relaxed, laid-back form of Hip Hop, typically instrumental and influenced by Jazz Rap and Downtempo.',
        hard: ['hiphop'],
        soft: ['jazz-rap', 'downtempo'],
    },
    {
        type: Type.Sub,
        parent: Type.Super,
        label: 'Lowend',
        id: 'lowend',
        desc: 'Rhythms driven by steady eighth-note digital handclaps, rattling bass, fast tempos, upbeat sound, and laid-back flows.',
        hard: ['hiphop'],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Super,
        label: 'Miami Bass',
        id: 'miami-bass',
        desc: 'Sustained Roland TR-808 kick drums and faster tempos, along with a distinct Electro influence.',
        hard: ['hiphop'],
        soft: ['electro'],
    },
    {
        type: Type.Sub,
        parent: Type.Sub,
        label: 'Atlanta Bass',
        id: 'atlanta-bass',
        desc: 'Originated in Atlanta, slower tempos and a more melodic approach than Miami Bass.',
        hard: ['miami-bass'],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Sub,
        label: 'Tamborzão',
        id: 'tamborzao',
        desc: 'Adds Afro-Brazilian percussive elements such as the atabaque sound into the Miami Bass kick drums.',
        hard: ['miami-bass'],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Super,
        label: 'Mobb Music',
        id: 'mobb',
        desc: 'San Francisco Bay Area production style building on slowed down Funk (often utilizing live elements).',
        hard: ['hiphop'],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Super,
        label: 'Nerdcore Hip hop',
        id: 'nerdcore',
        desc: 'Themes touch on such nerd mainstays as science, computers, and science fiction.',
        hard: ['hiphop'],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Super,
        label: 'Nervous music',
        id: 'nervous',
        desc: 'Dark, sinister and menacing sound, heavy sub-basses, simple melodies and slow, sparse and slamming drums.',
        hard: ['hiphop'],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Super,
        label: 'Philly club rap',
        id: 'philly-club',
        desc: 'Mixes the fast and energetic production of Philly Club with similarly frantic and fast rapping.',
        hard: ['hiphop'],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Super,
        label: 'Political hip hop',
        id: 'political-hiphop',
        desc: 'Features explicitly political lyrics and themes.',
        hard: ['hiphop'],
        soft: [],
        bands: 'Zack de la rocha, run the jewels, 2pac'
    },
    {
        type: Type.Sub,
        parent: Type.Super,
        label: 'Ratchet Music',
        id: 'ratchet',
        desc: 'Features explicitly political lyrics and themes.',
        hard: ['hiphop'],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Super,
        label: 'Snap',
        id: 'snap',
        desc: 'Prominent 808 bass and finger snaps, with lyrics primarily focused on nightclub topics (such as sex, drugs, and alcohol).',
        hard: ['hiphop'],
        soft: [],
    },
    {
        type: Type.Genre,
        parent: Type.Super,
        label: 'Trap',
        id: 'trap',
        desc: 'Originated in Atlanta in the early 2000s; distinctive fast hi-hat sound and heavy bass at moderate tempos.',
        hard: ['hiphop', 'trap-edm'],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Genre,
        label: 'Detroit Trap',
        id: 'detroit-trap',
        desc: 'Emerging in Michigan during the 2010s and incorporating upbeat 808 percussion derived from Trap music and dynamic, off-beat flows from rappers..',
        hard: ['trap'],
        soft: [],
    },
    {
        type: Type.Genre,
        parent: Type.Genre,
        label: 'Drill',
        id: 'drill',
        desc: 'Originated in Chicago in the early 2010s, broadly characterized by complex, energetic rhythms, coupled with street-conscious and often violent rapping.',
        hard: ['trap'],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Genre,
        label: 'Chicago Drill',
        id: 'chicago-drill',
        desc: 'Bass-heavy, dense, and typically syncopated percussion, featuring ticking hi-hats and gunshot-like snare rolls, usually accompanied by menacing synth melodies and violent Gangsta Rap lyricism.',
        hard: ['trap'],
        soft: ['gangsta-rap'],
    },
    {
        type: Type.Sub,
        parent: Type.Sub,
        label: 'Bop',
        id: 'bop',
        desc: 'Grew out of the Chicago Drill scene in the early 2010s, characterized by autotuned vocals and upbeat synth melodies.',
        hard: ['chicago-drill', 'pop-rap'],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Genre,
        label: 'Free Car Music',
        id: 'free-car-music',
        desc: 'Chaotic and metallic percussion with clanging rides, rapid hi hat rolls, and tense kick buildups typically coupled with staggered, punched-in rapping.',
        hard: ['trap'],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Genre,
        label: 'New York Drill',
        id: 'new-york-drill',
        desc: 'Emerged in the late 2010s, characterized by energetic, bouncy tresillo rhythms, creating a warmer, more booming tone than UK Drill, which prominently inspired it.',
        hard: ['trap'],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Sub,
        label: 'Sample Drill',
        id: 'sample-drill',
        desc: 'Prominent, recognizable samples set to tresillo-styled Drill hi-hats and counter snares.',
        hard: ['new-york-drill'],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Sub,
        label:'Sexy Drill',
        id: 'sexy-drill',
        desc: 'Emotive and sensual melodies, samples, and basslines set to driving stomps and bouncy Drill percussion typically joined by lyrical themes of sex, love, clubbing, and heartbreak.',
        hard: ['new-york-drill'],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Genre,
        label: 'UK Drill',
        id: 'uk-drill',
        desc: 'Deep bass and complex rhythm which denotes a Grime influence in the production.',
        hard: ['drill'],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Genre,
        label: 'Futuristic Swag',
        id: 'futristic-swag',
        desc: 'Playful, Snap-influenced and party-oriented.',
        hard: ['trap'],
        soft: [],
    },
    
    {
        type: Type.Sub,
        parent: Type.Genre,
        label: 'No Melody',
        id: 'no-melody',
        desc: 'Usage of minimalistic, repetitive midtempo drum patterns, and simple, prominent 808s.',
        hard: ['trap'],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Genre,
        label: 'Plugg',
        id: 'plugg',
        desc: 'Use of sparse and compact drum and hi-hat patterns, subby 808s and heavy low end; commonly features piano samples, airy pads, and icy synths.',
        hard: ['trap'],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Genre,
        label: 'Ambient Plugg',
        id: 'ambient-plugg',
        desc: 'Strong atmosphere and texture taken from Ambient music; featuring tight drums and minimal low-end and 808s.',
        hard: ['trap'],
        soft: ['ambient'],
    },
    {
        type: Type.Sub,
        parent: Type.Genre,
        label: 'Dark Plugg',
        id: 'dark-plugg',
        desc: 'Ominous, sinister synth pads and lead melodies, skittering hi-hats, and fast percussion and snare rolls.',
        hard: ['trap'],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Genre,
        label: 'Pluggnb',
        id: 'pluggnb',
        desc: 'Emphasizes more melodic and layered synth leads, denser and faster drum programming, and a lesser reliance on the laid-back, minimalistic atmosphere of earlier Plugg styles.',
        hard: ['trap'],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Genre,
        label: 'Rage',
        id: 'rage',
        desc: 'Dense, buzzing synth work with repetitive chord progressions and melodic synth leads.',
        hard: ['trap'],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Genre,
        label: 'Rare Phonk',
        id: 'rare phonk',
        desc: 'Primarily features eclectic sampling and lush, jazzy beats, usually set to Trap rhythms with prominent influences of Memphis Rap.',
        hard: ['trap', 'memphis-rap'],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Genre,
        label: 'Regalia',
        id: 'regalia',
        desc: 'Lush, sweeping string arrangements, dreamy piano passages, and other orchestral instrumentation set to cinematic Trap percussion.',
        hard: ['trap'],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Genre,
        label: 'Sigilkore',
        id: 'sigilkore',
        desc: 'Dark and hyperactive production, featuring rapping laced with layers of effects.',
        hard: ['trap'],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Genre,
        label: 'Trap Latino',
        id: 'trap-latino',
        desc: 'Distinguished by its Reggaetón and Latin Rap roots, with smooth and moody production inspired by Alternative R&B and Contemporary R&B.',
        hard: ['trap'],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Genre,
        label: 'Tread',
        id: 'tread',
        desc: 'Icy or futuristic synths with busy and high-tempo drum programming using distinctive 808 patterns.',
        hard: ['trap'],
        soft: [],
    },
    {
        type: Type.Sub,
        parent: Type.Super,
        label: 'Turntablism',
        id: 'turntablism',
        desc: 'Manipulating and re-appropriating vinyl records using a turntable and DJ mixer in a Hip Hop context, often featuring constant scratching and beat juggling between two or more recordings into original, distinctive tracks.',
        hard: ['hiphop'],
        soft: [],
    },
]
